[[Clang]]
arch = "aarch64"
git-tree-sha1 = "c9828f0ef0f967487ce376a3d8b4c8a646d38ace"
os = "macos"

    [[Clang.download]]
    sha256 = "c74044dda34e0801aff0d8a4de6b0a373164f67d3f3703b98e9c3c315be03a4a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "171f7c191d4b6cd7663a400d72d8de573c134e76"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a46e2c91b3c9e23b8bc6c23ae1ba9461e8afa271dca48e6b5b2d22345e131a1d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7fe3b79a7a218b51b266324692d2285ea1861c0"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "41213bbbba454df58f3a8a223ac4b3890bd3fe0e8a532176e7de3cbffd9db67e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb4c2d4f45b7b82b8f683387c07d3c89ae862c08"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8bb063a6b5f239bc9eba967c94014324f56ba82bf0b5d65159d24d5687f925f4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04cf71715ecca43f893b10dcf026ef2283c946f0"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "7e7d193f5fa3bfb486372acef11e6081e7098fa393d06fe1917d098dc4a170fa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb54be759c6545fbb32399e83ff9a3340ecaeac2"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5c12ddad971c58bbccd8f95d5d93e38aaf8e9911f333511e6acfb6f2cd5653b8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d357b1725b6499582891ee395d381844a469932"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c7d49daaccdf69d746cc3de41161da6daba629b5b1daa17c064ba740cdfaed4b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abadd952ba2502aa67450db82662949cd2b9072b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8d9d393067c883db777d144aae21e462d8f4d84c6c6dcf033f7c142df450e28c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2597caca4f47e25d39d64e87dbf4262f9810da06"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8918098bc6fb287abfbd424aee387b87564819040566d84cca346240a10a3271"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0545d74055cf157777905c90ae39978981ec139"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "77f3038c187d0123556d250c7b660b4c31cfe05b1b92658c851182e007498b5b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec6a50c7c4878bb7c8c73c386c278ef32bfd8575"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "50804c131fc6d6fdc982b4e407b63fcc86f46cdc1da0d485da78e378cbe8374d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "063a3ceca8924f7f675f36aeb57b58d8a9067d15"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "48e8f132c4b14ae03e79568d3a009e16367c51e23344846c74f3f538fbf9d371"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e29e432da90380f2e56d5134430baff7d89de40e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "0b9b7e9c6f2c4aed4115493b4e9d228f03bbd33b04bb71e68c64918a985078f7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5576ddcee0ee0114daf50dad9d9ad2449d51c49"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "0625ef3d59e4ccad661a884aa36b95f4ee974213ec52b78a9cccff10860d1413"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84e6b9183999a031375bff7c33f8985e269a1f51"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c800667b8792328f99a2327e0308df92812f1f4dd35a396f88efdda3060226f5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a074e668cea1d2ccbbb2e82258948784ea286c8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d6d3b2f785d46855f22f4d25ab1d93ea9d3e84af1cf38caf525a3658fdb2c363"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "680e145aa4968d0c9c919d4f61fd5a692599def6"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a414284b8dc1336182a11cafac2f859a82a8f0134bcc655e04a0a743a48974d1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "638d3a70769d90aeac9ae84e940484dbfc80f0ce"
os = "windows"

    [[Clang.download]]
    sha256 = "6e65d028cb378ea19307d87916fad7adfeff731d939c9c66e08ffa322e7854af"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73ff84cff97fc639cbb3b3b7f01d1eb520724eec"
os = "windows"

    [[Clang.download]]
    sha256 = "e819e78e52617334f709314f9ab535009ebfcf4c6b42ac541df4668e6ad5fc5e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69d96121825abe812af31fcaa854ba3fd342753c"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9449b391807a380c727104d16ff55d199b334e78df256afaff68ad0c026f8afc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bf336f02ab6841519c40899266de0428670a609"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c892837e1d966959cc1ad354749d8621b09bb43e2bc03ab04ac442a9beead996"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "e1d7201e00253ff95f65683b8bd80a1f815364eb"
os = "macos"

    [[Clang.download]]
    sha256 = "dfc412d102ce726b2bcf35d475ce7d48c08195d82ea715cb1858cfaa9c9ddcaa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f845d3caac68e9b46ae9371cd2345c4450d287f"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "d87b62dadf451503d63bccbd0cc44484290a77e65f2243a453e0918b1d81f2db"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75ed94858c831a8af1fcfa5151509c116570ef05"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a343071249cfb766fb6ec69cc21b72e3c9b2b1427b8020e5f685d2feedea3588"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbc82b0f3e35acb2af5e00d8f5dca1239c76ae5c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "01fb25a44c19389b90d5c3e720a977681d0f3c28278afdfa32001153c1502b7f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95d493b79ec04ee6224002b365e351552b4688ad"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4111c4d58fb073b3c245b75ac2cf5c4b251f30649b74776849461f7b69ea17c5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "779ffac023b4eee518c7507b722880cc992b15f7"
os = "freebsd"

    [[Clang.download]]
    sha256 = "c87e437419c9f2e6f8d7bcc5ba705999cdeb2ff097585ba6bb56db6ec18e0e4c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "186a301769c9ff3f5e607f9bff6da065addbdec0"
os = "windows"

    [[Clang.download]]
    sha256 = "e273aa091ed4a670f2e500cc49d8548aecc204a6a7254b5be5ee568c9a65915f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "081cbf26246ffde9e4035a3cf7e1924762c1dc10"
os = "windows"

    [[Clang.download]]
    sha256 = "1a1011a37418b32077849453e869229f1f5a0a73823fe19a3c49e1daf95b55f1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+3/Clang.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
