[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b0fe9970d98a4f981d3c8139c26c1275bb87a8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2e2d7e17d27768caa781aa8d8f9973525fefc122ebfa26e5604f89e8c95d224b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4318f6c419b88aea54fc006ad4065872780d192a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "14a8baafeab8adb9608407b8c1a88a8f08a0a4725da51aaa31e1873068fd694c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c1958baf7d33bf16e10fa96051d3d62dfe63ad8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9f86255fff07f04599143e198a331585917966416b71abd378f560d5ca5fcd2e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "774d3b7127c9bddbdb84eecc63e03762630d05ad"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6b597e4e5e4ffe8bd06280347b95e50128e9ef70215279f24a1c6d9578cf7e50"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0eb78834672fb870f4b1ea48436b48308898f9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "6e4b202d3114026478c6dadd4ecc66deb38b394fa1c34c4d19540796424c9040"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fc3ff57692101a729211b7033bb4f22f07ae4a2"
os = "macos"

    [[Clang.download]]
    sha256 = "214349dc3507979b89563bce403eb5ecf02dee4807f0f6d3bf4558857201790a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9823d67b3964a723e78c6444df468857dec633d6"
os = "freebsd"

    [[Clang.download]]
    sha256 = "a3209751254e0cbfd3419f5fe3dd788a4683f7cf66890d9a4cdd920c49db5e15"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c16254c3373e9f8752795683645562d6a8e75f7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "005623d694f88d3b705063a197afb4ae6be1edb8daf27b631afdc0b708ad63f3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b3446c80936628fc15704410a45338b14b8e965"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "26e889a4996bc4f944588f011be887d8c4f6d11953255e557a6ab6c7923ed90e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "038fd29a2cba59e5dde4d6529ed8e37f19eed480"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "243c48caaccc4f2a6606c5f17d6ec2b75129a812ea9bdad146b6d6467592276b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df5e03d40bf19d8c3844a6a4fa3103d0c360251"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f77dffdc20815a363924cf5099c51f06d6663b9d5f60fd646c3139915118856b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20840f498be7ed5f38b7607562533a8f9a312202"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "547e8b60728099d3271b621d66c0927546c0a94013b820bb9936fd39c9da5251"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82135c23a2827e2414051a5977f0e048c1c55221"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "98f87bc35f98af712cf34c6b1aec163f21d272765c676b8a82e45a6c8863b0fa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fc3ff57692101a729211b7033bb4f22f07ae4a2"
os = "macos"

    [[Clang.download]]
    sha256 = "a680e66a262c9e70f8abcded0c9a02daa17606f4ac5f76bab7f3cc3a547fb23d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00ad9e8d81e99fe1c90625509e2c280c67b59bd8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8502f05068b57cd2a14fbdf3fcd1acda5c59c337ef96e4efccb0bf5180a5781b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11d73871076a4b50369d4bf7066fdc65ed8be9f7"
os = "windows"

    [[Clang.download]]
    sha256 = "c96a410628b38d543ec55d41e0ee850fe39210646645fbef3ad89c8ffeee99fd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "899e8791696e8e7bb2b561167fcb1748cd6ff0c9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2955147c83e7bf41165666740897ba6f919572699796f695ac5c9153dd74222f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a006be925d7ef802d5ab986441736e92cdd36290"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a8161341b86d871d852907eff3549db6dd3aab9e1df00e7cae87cbc5826b5b36"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee45980e6fd489d8231b621ccb2d918a74c37324"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e232f55e61f9c8a539bdedfc16919b96016577d582de969df8fab1ee95c6eb7c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d03a2cbbce8104aac29c3291ce443c45054aa4c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "f82fa446e54d60575298be2676c1271d479dc4c1b4034321f1d0b495c60d06ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4a3d31df91f66cd6bd9be6a88f7af08403a68a4"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "02986d1be8311fc4adc7399b28da36676073cb5266eb443a981c8ee6f3b297da"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cccb99da8689598be090d7e0706b64d0d1bd5062"
os = "windows"

    [[Clang.download]]
    sha256 = "44178094ff5dbcf612b52adf104643575e217d763a6d4970d8cba2477e6c04bc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1eb346b985d04da636f494443dc773bb3b1030c"
os = "windows"

    [[Clang.download]]
    sha256 = "f89840f6041b277caa63cb6a54af35f7810748e5c09e158a95c679c0865c18bd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d22b052687f3443f702c8fe1110022e33d7105c2"
os = "windows"

    [[Clang.download]]
    sha256 = "60612c3670089b659fc667cfd4d71b1552e8e241d7c6bb779811ced2e47c5579"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed67ed0dfe50d2ee018d4d135421af6cc209578b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "086ef489b557f8e22e0c91cd473d058581da9a15f19fcf9e7b1f8f80ffea40b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9823d67b3964a723e78c6444df468857dec633d6"
os = "freebsd"

    [[Clang.download]]
    sha256 = "6968566a1c644bc2ba48aa879edfaf107b71c90a854e6af7a925f557e69a06a4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "0c16254c3373e9f8752795683645562d6a8e75f7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "21bc29e5fdc8e2a7a90217bd3e11b8e7e7ecd16943d58482034d1d47203cf8b1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu.tar.gz"
