[[Clang]]
arch = "aarch64"
git-tree-sha1 = "2a580208fb6f3c0025b9dc5cfad9479bed65ab2c"
llvm_version = "22"
os = "macos"

    [[Clang.download]]
    sha256 = "234ce9efb22c39dcbf9063db0824d75341e02494439e06283f1e4987d7570e96"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-apple-darwin-llvm_version+22.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5853ee245a7e677df8d542396212666e29b7450"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "2bdda5ee894c92b51a677853d856ae7cc94d2df7c79007ce3755ba57ab682c2a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fba4b7597c2422cdcb6ae2b88bf5eb40053e72c"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "9a372b9a2c7380b6757a6984ae1c1a2924e2f0fb8551c53d0e0dc09cf7190969"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-linux-musl-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "2ce486d4b62254687b9cedaa63a2afe04a97fdd2"
llvm_version = "22"
os = "freebsd"

    [[Clang.download]]
    sha256 = "6487a37df33e87bd5df6d0b991c788c702cfbacd3828a3b4ec8d24c013f1d644"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-unknown-freebsd-llvm_version+22.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e783138c35126d4104c9bad1bfaaba08cb21301f"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "7e818564703670dbb0066e02f87770c27d978c1af48868b487c08e4fe852661e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e2503417230ca2bbb1b7a423c79b5dacc0620a7"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "908967f8ab48dec7fb4f9a8b366aacdc7d921f83b16fd6ac2d24a9453a16511a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "230c9067babb2a38b379c2d632dc2e95279fa2e9"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "f0603dc6d514f8216cb007df2531d56407490ce4155de11aa684927cead832cf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be00d59c6e0efc3e3d70a8386707baa1781c9f6d"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "6082789dea22630719729d70ee893685d44df63531c02a62824c5aea2b12e321"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10710c99ede1003ef764a5373a9248de9dea7799"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "850801406d52afd76fe311f2ab747e712b2e9ea11f4cb75df74baf69b0ee8456"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.i686-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03b7a53426b1fa7994264a4617660a1f279aa61c"
llvm_version = "22"
os = "windows"

    [[Clang.download]]
    sha256 = "03c98b764f16318a5dd77f76b23a37e2165687463fbca5e70218d2fb43b29177"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.i686-w64-mingw32-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a55431670b544471840cd842eeff9ee52890ae67"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "e973dac72889fed7b3be35f4e7d6063f18c4c4577091bd19b57fda2c71bd3a0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "838fc83f0ed06b190668864df3e53d4ea29c5857"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "ade812299c7af021ec900d9acdc10d7321c245f3712b6ebb659797b84e45c548"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.riscv64-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "1b99ec2504c0112ad4b88251c2cbdd4faa1919b3"
llvm_version = "22"
os = "macos"

    [[Clang.download]]
    sha256 = "772210a34df2095e01ae0bb054496f2e51c921e80a343a9cd3d5fae1663a45ad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-apple-darwin-llvm_version+22.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99bf039ab19a7e1bd8fea1f58471b49fdd8d06a1"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "ebc5dacc1c3989db81b5103b36cf95448a9892c08b7c6eb2de6c34d3b2ec48ab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99bf039ab19a7e1bd8fea1f58471b49fdd8d06a1"
libc = "glibc"
llvm_version = "22"
os = "linux"
sanitize = "memory"

    [[Clang.download]]
    sha256 = "ebc5dacc1c3989db81b5103b36cf95448a9892c08b7c6eb2de6c34d3b2ec48ab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+22.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70bc7c8134e1b342c482c0daff0074b581c38270"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[Clang.download]]
    sha256 = "4b633d419c06550fa34f6fbc38519f5b0cf25d81f907c1bbad21e9fb2cb7aa66"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-linux-musl-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "eb881f061e5dac81b5eb1c0c8bda507a2c73c47e"
llvm_version = "22"
os = "freebsd"

    [[Clang.download]]
    sha256 = "09224e1626fd1c2c5bbf1a181d80baae9693a92813a0bd0da1bbf60673f8c668"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-unknown-freebsd-llvm_version+22.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10a14995cf2a79cf4cf277a1017d24b877ff4439"
llvm_version = "22"
os = "windows"

    [[Clang.download]]
    sha256 = "cdb93873c8af3bf8e5b61fb56b07600f55a8be642c65b0ad1f19ea693a6f7e11"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-w64-mingw32-cxx11-llvm_version+22.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "f8f371936582ca9e425261e37271f54c07c57ab4"
llvm_version = "22.asserts"
os = "macos"

    [[Clang.download]]
    sha256 = "b74fcf8d6395a349f570adff5f3839c538324ad5068c188d07e0289f0285d792"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-apple-darwin-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1223787702ff594ab61753cc922766ab0d224bf"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "3aafb13bb94c99d88b3525933460ae83aeae8fa68c16ca276dc6d317d14afd8c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "208e86c6e80eedcbe05b373879f5ea72b7b1ea58"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "f8ad0fbf3a123ec2928a2ed15e79009a0f8d17b8d033ff59d4323b856a709b2b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-linux-musl-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "9bd993ab3a4a3d09dbd806ec07cfde356dfa2b5b"
llvm_version = "22.asserts"
os = "freebsd"

    [[Clang.download]]
    sha256 = "44ca06a962b3057329c9b2ee08aae4767e04948baf6277d1be10b21defaa4b8d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.aarch64-unknown-freebsd-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9df5cbdba8ceb34ae54805fb2796d62f9c56e1f"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "fee94d7a9c7abd6d51cd8adcb90494bca95ce268db659b4e5cbea9d430b3b610"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd1082e44bb51542628a6e69c04e1a4e7834c15f"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "357e03a707e971b34d69d1238cfd92d4b295eebb334100b4995b21b180cb02b4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22cb57e555f6ebecade2376f224f131d3c6f46a1"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "57ad330053afc2b91efa9afd2651f2faba467a3e2f62b7fd0dacab280db3b438"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27219ce9ddb20ce8281b4aa440c0863e2e5e475b"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "e1a16ed10ebae6ea93af07dd3d20363e590c126656e6082fb256b27fbdea23d1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10ba3f92f8e417af0eb6114b89bb1b0280b59042"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "5063f844b4a41dd18ec701b3d17cbca94c5437a5216bbc7d462c5fbe32a75904"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.i686-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8e3f76cdcd14096285d9c6919e8589e8493f06a"
llvm_version = "22.asserts"
os = "windows"

    [[Clang.download]]
    sha256 = "3d9a162c2bb15eb5fad699f04cc7336eecfa912e5931c84db9d47add17d5e072"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.i686-w64-mingw32-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c6538550fd5fea5732582bc77298602393d5702"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "a0a061a3b8d096a7cd48d9289afdab84a1e83abeaddd2e3eeb7ebfd155eb8212"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7a4b100aaeb826a1d50ed25d9a10c060ef96781"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "9a7bd72c73243f11e58e45e502b50bd9f21b860aa9f71cacea9575ba244cfc40"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.riscv64-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "52a2208a6509b33cfe03e17e60de8490bc914d48"
llvm_version = "22.asserts"
os = "macos"

    [[Clang.download]]
    sha256 = "3c29a6e068607a401f95423445083543327fd4955d9d6bbddfa77ccd62ffe563"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-apple-darwin-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e87cf839798f25468c7ae7ca6b1a3243f5ded0d9"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "7aaf14fffb5f439d451c180afc94ff6932f7080436848b5484051f89c35f3ccf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e87cf839798f25468c7ae7ca6b1a3243f5ded0d9"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"
sanitize = "memory"

    [[Clang.download]]
    sha256 = "7aaf14fffb5f439d451c180afc94ff6932f7080436848b5484051f89c35f3ccf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0635385139cb08bb7411bb4a4dbfe84fa9f926c"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "f5ab98c63f41cd7066fa0c1c8a9db810b7269e3704b7a2251a91195094837f29"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-linux-musl-cxx11-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "d64912413576de796cd8cecd7af4437a6be485db"
llvm_version = "22.asserts"
os = "freebsd"

    [[Clang.download]]
    sha256 = "baaa3508f041b6901c716eee1c91e8e35aed8f127400d07347e835789c98a3c7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-unknown-freebsd-llvm_version+22.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46f854e565da924551c4c0656f02e077820c42f9"
llvm_version = "22.asserts"
os = "windows"

    [[Clang.download]]
    sha256 = "45fdf8f733e89e9b266a3a01390b0759259500fac8cfa6d364125270bc21f336"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v22.1.8+1/Clang.v22.1.8.x86_64-w64-mingw32-cxx11-llvm_version+22.asserts.tar.gz"
