[[Clang]]
arch = "aarch64"
git-tree-sha1 = "425a71582560c020ead54ccce8f1fd33af1a295f"
os = "macos"

    [[Clang.download]]
    sha256 = "99522e5d9ee059109c7ef4bda17d6f3b7232faaaff730e797efae810133e15bd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ac6fae4ddf7e701718518eb40e6dec786551fdd"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9d67ebaec8d4cd8fa554de662a0ae73b194c6fc71b1c00259a2ba156de07c59d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88d5ed91961557cb8a901ff584daf9348c59cbd3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "39efcd241d2471eec8101869605d4164b8cd27eb55d5e3a83bb1b107ceb369ca"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3a38f21ba429def4aa9b7371543ee7cf8d2027c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "86ed999c5ec2cfcb748626f1840a51fd82833048dbb337619bd5630df3ce07f9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1433a8bd511314ef6c1216ed16b290cd932e8247"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "be053fb380284bcab822fa43e7e4d708f6eca05e49dce10fd232a9d735fa6d9f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03f3998b9a9b42933395bf881bb19119668a266d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a1a3d35bbca5c52c691ce29a4a15ef54685db606981c5c48672ba5de99f69101"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e9c2438ea6a037265b25f2185328ac9a3237ab7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "43048f59f76312878f94ad364e1424b0965ab9f87d1972445fd9ebf4f31c2474"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "463ea34b76adf765f25389cee46e522bbc99b86a"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3185be6c3f4c74a60540c2af1242a3b464fd6601c4dec57c299741016cc0aac7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f02c44b130bd9af9404670a422be310af4007937"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8ccb752242956358c07b486250f7617594b5d3ecfed9287facc6d5d883add268"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a07f13392f003a870bd7a9b138b25a088112a4c5"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c4a50a756a33e55683f51ed5d24bc64be170dfb7b70f65cf413f3e216ecdc453"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81b5ce0f4f9c7dc51c6097dcf142cb0c3bed4e29"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "534efd96283bb92feb9b350aa2f644086c31da4f6670a07e8ffc0ffeac0d0d39"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8a0d8ca8411047cf968978ecc4b4c618e599889"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2758fd527e939339f3905003e1bd927344bcd4ecda3b62b91b87966ac6781247"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cca8dd6d42580f712c48c8f436e17ca4bdf3d39e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "913e26b7f69fa865a82bcb4fbdb14194982c4b7ff7e08afbece691fda56babc2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d28e723a73ea3d7193fde7eee3da9e75876e986e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a1ea91f63bba3902706f116ca4f35dd8f12445a2ac6b8ee627b7a323b216dfad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b905c2d11e46be666b3068674687ec56d093673"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ce11a703565ee7749c3031f9d3a3b60f09e0f21810fb8aa642b5188007457a35"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4125bdac4643af4896bc3a73d1ba1b1230bcebbc"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2847c5f9fac81a9dd08ea84b5a07033c479dc98660a60703925e8628d5efc1cf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83445b9fd4395695e960d88beba1cc3fa4b52b4b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "572110b18a642dc7b1ea9443cfcaf4ee54c18b26e293a7b9a7f02dd6c761839a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e57460591c2b93c951cfe51d318559ecc539a36"
os = "windows"

    [[Clang.download]]
    sha256 = "5ad8c3b0da9546e48251289c14fd7f59d57692038b1cfdcad545e447506995a2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d48addbc25f6e4b369d910955deac7ea138db21"
os = "windows"

    [[Clang.download]]
    sha256 = "e706e1bfd786b0776da0b3bfc78c8f286f7b1cc3e4652a5692ea955506bf9b4f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddcd63dda98eac97966d0450bf3d68a281ac71a9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "249a4b0c2de78e4283b31de1732fd0190e61c6920d7edf785aeda189916396ff"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2db205dfa1b439b82b477da1cd535a75d28ea805"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2260f7e120240cc5c9959bf9da366fc91621202b5502427ab91a853976d91a32"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "bfa4d0193f6a8c5a01c09cad0c569c88a4785d28"
os = "macos"

    [[Clang.download]]
    sha256 = "057518569de58687a04118df873f77915926abc2f0e5a7a1a2373ec5a756cebd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bf0229df933c70dae01885b9f80e07e2759de17"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ef3ab9c2c3462d1f141caaff979ad012d2a361087501c72c3ac773c551e109f0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31d12173811faded0202374707737afe6162bdaf"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "891fc6b444aa1f5be85db0b92b2c807ff5ad3c87b754e10c6ec7346dd769449f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eafd54fedfe79cc4cd76b65ef7af50226b6197d6"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "51518176b527eeb716f0e93dc9d2ed28c25a8e1b0e590e963fd6fda46d0a6035"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42a922690ca0b97c071ff6216fd811038e3a3b80"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "e069b408a521a6cdaed634d7814527fd0855c562b10e1ec8bb8bc2852aa8885d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "b556e79fa19eeb0156f4939278c47bd1b6b8d033"
os = "freebsd"

    [[Clang.download]]
    sha256 = "e0079dfeae69094c8df232acd56db4419d7cde8c244069fb75e8f5e48b7f40fa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8eea417146698c8f9b7f6c3d5bf3f08f1afdfa1"
os = "windows"

    [[Clang.download]]
    sha256 = "0ae3c9902c6dc3e2404fcd245d20a78edf4db9be60e073035d525e10f63c2276"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5243dbd287e610ebdba7d886bc54aec181f6d84"
os = "windows"

    [[Clang.download]]
    sha256 = "23e83ad4fbc064c00bd1a3687c54d8a139e6e238c740f28aabaa24cad01cfd0c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+0/Clang.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
