[[Clang]]
arch = "aarch64"
git-tree-sha1 = "1af4fb7f9ea291ee62088508be99dcce1c2bd956"
os = "macos"

    [[Clang.download]]
    sha256 = "2bcc2bdc3db2b4c2faf05b374e632f753e4d4b39d1fb209882e38590b4619373"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f33cd54da9ddba4d568dfa312c7a554269433305"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9eb3fd661a064d3120bebd0329a6237df407e7b90f455555e54960fffe20ac22"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eeff7adfbabe8b63574d118a7a95b101679fb69"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "119a5417afd6ff493472f85848fd4931d80119a9f44945f36b086ab18af3e3c5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3feb30e6a798fbdecf101c0836115d69b6c5dc8e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5a44fdda0f226ccd058f59d00f2d5e1fb3cdc88329ed4e205b254e4046324ced"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "032adf28d83a4eb169b581a7e29c95efc2dbdf58"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "baa05704efdbdbe8e536226351ea27e4560826644665417495529270d7e7acf5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c2e564fb5af6908ccd5a8e9371f2d29721c4a96"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ef65b8946a388be1ed26227bdb9a3a3ec81a2858574ecd9f5e6334169beaef60"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0da491c1e792694c8ddb2404e10a69856a35182d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "45b3708171fd8c8563bdb0d748b4fb01080e7817089e8abad659d80b33ba7eaa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f6cab590ce77ff504c72dc8262ddfee6f086c0"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "01451e92b84c4ef4da742e4ee7cffe1a8e00bd2629541f84d4ba152f8a087519"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee1af8ff123dcf02aa26e43f944cbe40d50a264a"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d9ae8df2545b3a32ee60fd0e61344cae7200312509dfde83c14e1a4f07f4df8e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75b79802aad15b23a37d106b73a2f923ada4e83e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "70d42affd28436d284e75ce43d8e87a4df2241be07c66e37c35a1c08c21935f1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38e99dd94eccb8dbc897db0f0d0fca3fda861f96"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "554338faeb097b255da0c5a651dfa9294e3c6777b48a682b00eceb4d61d6fc6b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b886476bdfa9e72b8d42ae5ef5911cc58464624b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "952d9b47956c275664a7b578edc7c50128fdbba7bdae55ec35843201d70c9549"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bb14f5b8bc7fbbbd2ef3cbacae9b6d4f8dfbf5c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "415ee83343ab2a34f219ebea49790c079bbf05987b9932f3f2cac7f6e7947af6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ce0c9613fb1686702084ae8bb094ec1c679a214"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f858fea9b34e378dfffa06aa645bc8bcb663fe1dcb9ccbe410d76c506a0d4171"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11ecfbc76054742240b17a2c7f1b8c92fa601eb3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c4b7d932892afc513cfd56a42578819b75999d6dbc71c901ee99412af1cb761a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0411fc623f5cdc0727eef6d7210be0ec1c3a3722"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2b2445ec4b14b8548d16c8bb64e772d536ec58541157662b4042667b1d3cac36"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a91fc398c71f99443041a7a97d22b6cb75a599de"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6bd256a228d1bf2cf399fa9dda7bdc31d4906970d6e9f05eba5ff3f545f36afc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea1908c438c8dd1e48aa45976f747db52f59ff31"
os = "windows"

    [[Clang.download]]
    sha256 = "87ac06890cf46aec126a9d4b1721c8ad0025c3f3ee7badc1acf0661922a36db4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c9e8b7f5019e9f832820b805f8343df6405a222"
os = "windows"

    [[Clang.download]]
    sha256 = "9b839a594bb0998c8883d3812b1a62cce9a3d480f4e35a17778f7bf2c9445198"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5002f8aba8ce7322ea1a90c3ed4ea2b411990b8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "65f1a6f13d4c3283702d0eb179f1992d4e106b13f7163d8e14979d3b53d7d273"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "262fc44f04029b2aee3df339ea636729ae64d213"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f85a18ffb8de3284b180eb08ac6bd7e605344cabb81a0e41bebf65b4e1e4a2d4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "482923ba4f0c0bc74dbde0b7a944c1db3d1f18f6"
os = "macos"

    [[Clang.download]]
    sha256 = "464210b7d785d13d0fe5ce23d7160c8ea6f91f33d925a538f6ffb86827239c29"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6aeaa3caf6bf7d7da97113d403537b3a23ea451"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b0ef643ab23edc262dc1ae35d881003f33de6196a9f4235229f3468dc7c3945c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88dab3027140e5f49b87c98cdf19f51a90e85c85"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "376de9a9ab8caf03e8dcef63a72a3567fbfe00d5476575ebe24f33ff773313d6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1a5ab43895f5a5c6d8b611f6dd01f3f01e03ac1"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "70432c1b71f9dfbb059d0b46925fe36cc870642c9316e50772afd4179b77cfb0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b525a6a5c81c13415a208bc54a5871e0c79aaad4"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "7be1feb64f8aba4dfb880a9e1a6a1e2206a237682169c5a02ca7c7db5ce50601"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ef1c3cba28c7a2b66e2e75340994473ef9e81a44"
os = "freebsd"

    [[Clang.download]]
    sha256 = "17bc29b981564609cb86438aefb4054618ae7b2f6541ddb97e3a434de9364e03"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3104e3c8d9c56e4fadab7af2f32a97a2a8cdb0d3"
os = "windows"

    [[Clang.download]]
    sha256 = "eb801d169692c0abd38e3fece465296732c22942572a16a2daf9664467eee920"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67002c6a3d782cba27a8c99aaf23df5829e5bb35"
os = "windows"

    [[Clang.download]]
    sha256 = "74813bf0432426fb90dec2f3e00c0929402f9a0d232c483a1ce0fcffcf2a8e9b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+2/Clang.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
