[[Clang]]
arch = "aarch64"
git-tree-sha1 = "b3eb91787ac1dd24a72cda84381d43807d264492"
os = "macos"

    [[Clang.download]]
    sha256 = "1e6b9a4d035fe068c7d40bccb009d7c7f37804d02644bf4db151024a1466a545"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ae8a6a6445a849c7fae6e271bb6c26ca35c046d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "31585cb6cb1c8fbdda6d340e03effb3dc8d94fe362daddb68657e47da42a5628"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e83a80b40fd2062bf3c8c743cc7895b506d5437"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8da38f1648cc828d2f462a247ee7de90468d555dd6b721e68d2c931b63d0e8fc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9134979cd9f11f57246d606f80a8e5061382ccb8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8a852bc7c7a068e2ca59f292e9506391077a2f93b4c0d1ce5665520e00ab620e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0895ea8a7452dfc99ce7440e99fc52adeaa761ae"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3fa96127b9f489aaacc26458bca8a7fe0603b6f5081cde5d9be8d8f19b2b84b6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d4a6ca035d7595825dc13306082d001da20168d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f7164b8ac989d7001911a1e14ed1a1dd9ac043944fcbc62513742081dd37c758"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f63961f69fd318e39b84aa4ca477ebf2647c6b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "49b4d5ed94decb48051a4a3959250e0c6f8849970fa0e394b6038d8d4afb88b4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a087f4262ddf6954e8730100bc533f2baa81a40"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "98943301981341e22e071614ddce95ccf3e0512f1dc67bc21c522010655be354"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f658fbbff6e8afeb29a4bb41ab7c8a65505b23f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b68854c46942c6fe7385d6fdc83dfb8a34941ffae2d4159c9a78d98061393dfc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56b448d025b9145c91f21406127c2fa050758081"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ebfbfd87b59efc661fc1592add0a51011812d7af71c7be4e436263186dccc445"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01462118da5af89e9bec97b6c93a4486b0b303c"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "32a62be251181c986e3b61178a194ca2ab4f91c96f933f5ef3c79774f59e20ef"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c55a1f91db07dbd7849ebbb123495b5b929c93f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "231a79350fc28f53ecc6fc860f8606c44ca62d9004db28e860d335ea4b9add9d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c48f93b3d323a72922eaaa36417e725811392e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a5de9b432ed59aff9543a455e4ca34fdf8fe80e5e32fcb85a970917102af639c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788013831bc029ecb96aa4f19579c2fc085c74ed"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "01112eff542c8e8b74f69fb050c70f21b0090027fc06fa6941f0927964cd07e5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18839b2869972f36a40545c74fb72c3c4addc0eb"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5235119460e4275633a9f78a22706b2dc1b9ae6e2fcfc11407d0a803036ae993"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0e70909d504365e2b70f68d64919d2151d479c7"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ca7dfb1008f0b08e0ab2c1a2903dfb25111b521d5f30cce86303dcd4cf2996ea"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe5e47c22efd5029dd74cef9041654b471eecd64"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "e6eec50b91e674a9f5e12a9f1bafbb53e50a2be500d9c66c18c534c8de2bcd6f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9e863f0aa266c8506910b1a1de24a57a2c6cfe0"
os = "windows"

    [[Clang.download]]
    sha256 = "42f32a5486a5858e6cf109a719f4a474ad0a24655706155771d214a68b2afa0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43c2d6f27f99cfd6a4ef484a225f5ba02813e18c"
os = "windows"

    [[Clang.download]]
    sha256 = "99caf5535474a442908dcf5817c225fb2b193c9cc9cfb7459ae08e315ab92c0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1dda18226dbea8a9656b19c1508ba579c7e5a59"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "aef0bbf9c829e79fea9464063f6ac5ba273f93c3a7704717ac1fd9e0fa3d0a52"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1dd7da41381eb0f2ecae21a0beb1186e8345010"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "0a0960283d0823905624cfe001a9e9567e1ebb30953d98282cab0cb5622a29f2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ed9fa3e6d1b2334758a402595755a9fa96bb85b7"
os = "macos"

    [[Clang.download]]
    sha256 = "dc1b707cba52247da074fafb44dde1dc3cf5292eb04dc4fff2df4ef01c9a4ddb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd41f6688856bc6cc320cc6429af2deca544a32"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "af6871f0cf07db2c1eee804224d94da3cfcaa21f648a56bca6c32a6e3ee7ba49"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8676d447ac19c510b147ae120378d2f57729b153"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8a4253db7e65fb8deab175ee1dd62a75466d3197f005d9e54d5471fd448ba088"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "883fa609cc671c23da59a8279bfc0a13f1160dd5"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "e1fcb445d91751e903cb9486d7c0cc735e190ba851c921564df19f8f6f1e425b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf1e24794e8c106d1029ac06c0c1a6960310cb2"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ff3fd4ae7daf9fcdaac4062e8a59c9455d591c5bf1d8f82e961ef62415b373f0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ae505dd4cfdc8b8b6be8280c2419e3da7fc46680"
os = "freebsd"

    [[Clang.download]]
    sha256 = "7f4a3f922d28ce99bf6ac25033bfc83ae88f913914166efd54d1736708584097"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47425386f0ada74543341967635b34637a0673e9"
os = "windows"

    [[Clang.download]]
    sha256 = "03682dd4dc02fc43633381503097f930f1ef1d734cc23b16d6ec47630f4175a5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92f245b403b123a8bc4f204f85fea787f12b346e"
os = "windows"

    [[Clang.download]]
    sha256 = "b54dc6616d506933820158e253d9e5b5e6a90b2d5e6bd7aa1d82cb21d67702b7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+7/Clang.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
