[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fc547f3add53473244af9f5c5df117cac6b9df0"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "09b03ca1c539213a6167a7d7c50e7824c84f11b8ae0099ecd3b23afff42a6de1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "825b2e27c78dfc830b4a344f0611be87610ec185"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "58b987010ee0a6710473acb9aa7c553baa44b6e9fd5e18c5920842737bda43fc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a0e709e21d700508700c69ca0e03a9ad57ed663"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a83066dd5ad4fff572b11c15957430dbfd2b8a5a88a390b9a2481ecc98eb13b8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "256efb462d08e775720516cd3d659371e347dcf5"
os = "windows"

    [[Clang.download]]
    sha256 = "38895b491da330e5c5aa2903fa8e9f605af1625d921b3ec0eb1cb771b0c10016"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b52f332bf2b40a702bb32b30c9638d8c5fa4f779"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3e35069939249cf81b4441cef24b9d028259214004538226abe91c4e7a3fdb82"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f69150d4f4e0119d88440450027ebb20b0181ccc"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "fed0e832943bc6aec1c9bc52fc29445f827f97c09c6d7d075e3f43a1450bbd54"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2eeed94866c8e3f85a765ba7fc6d1a830831b406"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "87d341c208ddd69614adf2ce7f70a3f56d79cdb9e40528fbe288b86fd9929a84"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abd58bd77d86fe4207fafe47cc8dc753cb523f1a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "57bc62cd72464e52c8b5904afc2f0cc8c1ba35145094f0ae71aa2b5212df1adb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "704440c5ba8d402cc85a951c59e3273e6768b2d1"
os = "macos"

    [[Clang.download]]
    sha256 = "1b46a83a11f5a4607a0d957ba81efa066eb32de9bcc328e72241810e0a6a4580"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "290cfd37e913516704530b623591b36f37a8a3be"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b26507b5b84baf1817772ae7dcb7bd17efc4522c845d1f73c435bde89c790e07"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1f780fed36b3fabbbd75263cfc9aff8b574d9f4"
os = "windows"

    [[Clang.download]]
    sha256 = "1b6050aeca9c4463855e37cd58b3cb172c95b78f243bbe57c7280acf9321d583"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1acefbcd90bde13810adc63c1a7340dc3e3df1e2"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2e69f05d4a4abcfc68e8a5bcf144330647610e6dd31a660c39d60c993a4311e4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e0ac8c44923ab0363807ff7b3de122b8ad46e52"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ee08a47fc8d0abe26fb1b17bf0461ceb3c96daac4c7c61a98b85142d0d2ad67b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37eb46a193fa07d6d07dbe30ad3b9ece1bd47592"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e8c0be74741480597b536f98b9e0b6da61db817539e0992a6d141d6f993f9770"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "947f6dccd7b363c7736903b7a0bf48a72f830a22"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "1870d40d22e8c1147db11a91225cb28711a72e32f11fbf18b099bf36d50707c1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "704440c5ba8d402cc85a951c59e3273e6768b2d1"
os = "macos"

    [[Clang.download]]
    sha256 = "9a53a1a172275fbd1bffae739dfd7d2dd41e6c9f3afb82247b0a975bafa59ff0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6163d75b8adc2da2c869af6d32131cc52f1cf7d2"
os = "freebsd"

    [[Clang.download]]
    sha256 = "c40b760c8dbdfe1b060df1a664a4b21ddc96a36ff5b94fc36d9d1ad90c571a3d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee9e586a2e59786bd9c4cd94fb7d7d94e8677538"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "4b93d6aa05217998f9a15faf046ecbd403388d0bd5018e7d0ff00a711b682062"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2eac368ee6a4f600fb8f48467ac185e642e902bd"
os = "windows"

    [[Clang.download]]
    sha256 = "a9991925e5b2fff8533a5449cb43d5b380ccae06196fad724a957378d505aa60"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f25e90d0e69e135016c2a87ae4ed7a675e83e442"
os = "windows"

    [[Clang.download]]
    sha256 = "eade4a5aa09f04bb143c9e9767a7c1c0d812860fbfb2033239ffacbc36165e89"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5bf15371a3c865b2f7997404850cf2e87417ca5"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b9f1976521e1c2253d5d85a16fcd337efb819d0e4defe7605594873b36245d25"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "431542ebecb9155fdcb250e4e5e8a7e607a1e4e3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "99c8596dd5b656de4c515a460c1fc9dc5a33bafc88bbfae4d4bd12c7a599d68c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3d17b7f80d2ab0dc476807483edd8dc129f2390"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c03482c4a06012f9d49c33cf3b274f9afddc23f4156b2821270eb572f78b680a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4224b88c84d2e9858b3b2e06bcb3e346e96ec070"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "6c240f575200cecd0178b4c3e2c09aa51f6083fa55601d479d862c463f4a10b1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68b0412c9a5167e3d113ea5bd7a23e0d1301df2a"
os = "freebsd"

    [[Clang.download]]
    sha256 = "a23920482312561c041796f68cb6b6c7c5123e39586c28ac1d369a6bcd515c93"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1166ac73d1b7b69b574fc99398a0f7b666a7981"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "c6ebd9b2835ecd00e59f670a51e4ad40788789c3168c0fa36adda81c26a701bd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+2/Clang.v9.0.1.i686-linux-musl-cxx03.tar.gz"
