[[Clang]]
arch = "aarch64"
git-tree-sha1 = "0037b6ebda85f782440835d2de9dcdf3159e8a3a"
os = "macos"

    [[Clang.download]]
    sha256 = "cf6d3c029d561cc98beaae38b5e2a8bc8d7f7aad57f388d05cf50650a8993910"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "927562cd4b70cd240462454d1e38ef5ae393113b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3e9713a6c8ae10c0cb8d530a2eda4fb020f03f331800ade1731211fa5ae76fd8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a754f1bdf2184c2439e17fae933ce6cf88c852bb"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "0f97b668627befb8f80a34416f591544e634c62d927af8618deb8fab0b6bb797"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ffda3526f209ad0348a970947360459ddfcd987"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6a0c93d34f11dd1aeb1eb689dd59bd687ca7f168e59ed7b982702f8f99d72688"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "312849a101a02922b74be9e503603629f11b323c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9d94acb62a56140f83f653bb1ab77a2cf54733af423fa487380e3ed5a45c63c6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec6fabe170524665f86dff41264a12c94b5c9941"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f05ddb9a79a485277a62b78df50b0f244cb62bed87db864a33be5302abac0466"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "859a00fcec0722dfb338780f5d02dfdc2d439473"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "296e0952e7485875235a707dad0c4755e512e87482210ad0a039e47147d65f9b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e03631ee8483de7bb3ac088aaa5c5464d985d863"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "75e1a30daa461b4e6f571afd25016bb9a25d15d8645e02da366ef2d27e2874e5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3858ff74668e0b64800477c795515da1fb114588"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2c172024e16df01ea6a485450525c778515dd2aa72ebd3a7f39a2e6e70b19998"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fc4cd939cb2fb4ebd2ae2523e54df9b82887eef"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "cf6e9331b25d177bb4d9eb7eb07cbe8fe613a5e69ab03ca8c133046c2be7b01e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15503be5d4812b956a1fcc0478197b7dd8b2aab6"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f2218c8621e2b5aaa20f2b48ae2767b9c3d917ba1402d7acb809cfcba29cbb1f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31f70f200653ad94fde76177c476aa594abf36a9"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9928a3b58d38893104eca427273ff9ebc4d964c3553bbb838864e2876cbbae21"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b699610c6dd5ab5ac30d737d09a6f4232daed30"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d4e5d9ab5c03db622b496b84c32d8bb64333e95f9cf570dd440ed4dbe9278d44"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50617f1f736468eefdaebaff657666e6895ec3d6"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "bb3540149729221da9e9c2ecc3cdb0b671f2af30b22e6e9dbe33e3b9fbe0351f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c1691809f1912b3060aba3e6bd7b9befe1fe6ec"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8e9089a8e6cceedc9b2af07b1f2ed532a17462dff25d27286f39a459faff1968"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a37ba3364d2a21751c706fe271fcf500ccdea72"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5b540c5a06e5abc77c8227b33faf13ad305d66fe845eca7f52a6fa8f0fd09745"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25479b198692a62a0eb07654de61ab51dd376d78"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9b13d1777d16991858bd926bc1c361a32be8d77f718408dc372b77afed502f42"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ebff6731154bbd6eeb35a669e287267eba6679a"
os = "windows"

    [[Clang.download]]
    sha256 = "c56a0294fc3ee047f22c9a8782fab7d690109da38d96d583a35b199e94340f4d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a1b8a343cf8f27df82746475f453c4225e8379d"
os = "windows"

    [[Clang.download]]
    sha256 = "e03524f26fa7930d3ba0150f057253b3f48da9048f0396a65cf5fba66c9059d9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cbaaa430d8986585d3c4dd1850b1b9d42c3ceaa"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9f65d8730c297802ab1abdc3c71d1be2471a9e0290bc6042a428b437202f8f5f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "752e41a43b9c6a9c0e90ce2793f81372f78978ab"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "01535276be379785beaf732918194abee81775b596d1cf11e9d8e4b4cd9355e5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "73b3f88d32790f8a714d1724e8fbeb4a2b3f42c4"
os = "macos"

    [[Clang.download]]
    sha256 = "594540886d8a7392d57e7c176f4493b755f7c5fdc43a2389a53312aeeb31c916"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dedbd36362701f6316c25d33ead83e5b2fede9cb"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a7efaa59fa55379c01fbf9a29d4998d79f09a2a8c3fad1ad65169b7be9c9b9af"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75fa93c094a795ec273a24cea9d9d6c1ee581ae7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "02226478efe08f8767118eea6485d5d88082de2a92a663bc7a5ac658c963b03a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "933a3c645c0bc99c3ba009ed9d56a8a86de28d3c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "f555aec9094b1773799d5917b34384c35a6d19dbd1230661cb99c541a42ad0a9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6e72b0057d7e5ed53a1d1f60dad7cb79e81ce23"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4410cff5cdf65cb0343213545d9b5537fd1457644e5652d8ab6f1ff11b139111"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "a046afd2eb14e0ed250de0edb59ffcb69334ee99"
os = "freebsd"

    [[Clang.download]]
    sha256 = "20c9b2f571bd60fd185472ef04702ec56795ce56ca6160249ad99335368a5331"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b6923be8fd03768ce6ac95decc06753b0d3833"
os = "windows"

    [[Clang.download]]
    sha256 = "1d9f2d8c0b63e319a98c64ccca4235c9da53a885eedb9aba74a00b38ec9922bb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43e5631610afd004fbd15362e98b840c5a13de11"
os = "windows"

    [[Clang.download]]
    sha256 = "e296e876018978598e33ebcc0c5a0789e19e565a1928becfbc335478f2208aae"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.0+1/Clang.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
