[[Clang]]
arch = "aarch64"
git-tree-sha1 = "f7115b6b921c8f4f9a4680de5b8314cecf62052d"
llvm_version = "20"
os = "macos"

    [[Clang.download]]
    sha256 = "9f0d17243af95271edc3ff91950b1656bf816b8a83ee4c821b0634f06f5f46e9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-apple-darwin-llvm_version+20.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b014f78725a20a257c86429b234c7fb295d2e78a"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "ac0d617375e09a7908f3a2635b30b29e74edada46700d1bec631e272174742a4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb86b4158e7c16e65d8087af26c66f96b829450e"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "d9709f5f814d85d45d5b4ffc0a8bbcd970a5ea8145a02879944f0372eb2a41bc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "2b9754517caed725bcc91457412e58d677e57a62"
llvm_version = "20"
os = "freebsd"

    [[Clang.download]]
    sha256 = "c9de3a20ac9c830b74a0cdbcebebf7495160fbce83b247cc4584810ef7aaf08c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-unknown-freebsd-llvm_version+20.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a67a9f9be0d38eefa8b1ff4eb1396c9f66fe2f6"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "5d835adbd606d05dd6345872c28b2122d981bf71d42f3264592cdd2fd61eac3b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b54b2d78f6ae37fb6559dca60f9c223f4dc40695"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "795260b2bb7a12a2367ecccca1d5491ee4b1438aed682868c8443406c12d54b8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e77cac48b6117ffc2ddf27c714bcbebf15c22977"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "e54bc08c7bce7cc7412c826bbb7728a48182bbd39b739e8fd066f036bf6e4221"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "402d00590cd49f0871453011f73f6ff93994fc8f"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "82a0dfeb0c218f5f8e8f90b80385e624f764ed86a22a6b916068c29049ac17f7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa42b5554a929f39342733b29fdb2a8ba9735d46"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "99e513eaa02dfe27817f1f65d53d0bf4f18f51b3909ea829dd822d62b242a973"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.i686-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89be08b6869231ba559c2c40ce9765ea90a25d97"
llvm_version = "20"
os = "windows"

    [[Clang.download]]
    sha256 = "f1d301ae9a061fdf1c1a479e38794e4fb249f94e24c990dc83427659f05e82fa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.i686-w64-mingw32-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e63c8b9ac4f51fe23942c1e28e87ceea2b39bd5"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "b9493145d02513c99434bf5efa53ad3f01c3013f276679c755ea3e40ee47d9e8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "035f9eea81ac496051c170a27f7ffa099bf1a5d7"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "2020de1f8bb8eb0863e2c61d6c506558d45b661ec43aeb05c49b5643191dec46"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.riscv64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "782039ef13df11e552ab1810c15aec0836ac8383"
llvm_version = "20"
os = "macos"

    [[Clang.download]]
    sha256 = "5e810d0446be757d07166ee9219ec7997d98ecd05c17641f030c552b2689ad2c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-apple-darwin-llvm_version+20.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55d3ac7b6ff84568263c620cf19d0d81e8296c74"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "d3657b24a31ee771a29f498729ee85814bfa5fe09453629270d522cc8ac9b586"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55d3ac7b6ff84568263c620cf19d0d81e8296c74"
libc = "glibc"
llvm_version = "20"
os = "linux"
sanitize = "memory"

    [[Clang.download]]
    sha256 = "d3657b24a31ee771a29f498729ee85814bfa5fe09453629270d522cc8ac9b586"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+20.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47574b93823c47a2221e1358a2e270018c91b9da"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[Clang.download]]
    sha256 = "c146a347e6e037ff9dc6f159b5e1a16e51a5fd2231210beda9f500b39eaf738a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "c36169acf811319d3f6797d938297165fd4f52dc"
llvm_version = "20"
os = "freebsd"

    [[Clang.download]]
    sha256 = "e38c6f0390c66652833585f808ce4c9da22399661c600951207b39f5106e8277"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-unknown-freebsd-llvm_version+20.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8531e388b402e7a61b7a90e48145606e3e90d29e"
llvm_version = "20"
os = "windows"

    [[Clang.download]]
    sha256 = "5b9b1661ee72c0df210c3097b6ed0d946b06e8c12cffbe50aeeb7548ff7aaa43"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-w64-mingw32-cxx11-llvm_version+20.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "ee9a189d4848a94825f27e390593bc98c149046a"
llvm_version = "20.asserts"
os = "macos"

    [[Clang.download]]
    sha256 = "2a45de6d3b3b23d64fe76cb8cf4e4339bc733806be617a66023b2cbffef6b4b8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-apple-darwin-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2cca6315e7dd71cf8fbc1a0f52591a120c6f5d5"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "44cb1ffd83c4a72ebb61d69a33386d6588ec15a62bedae144844d918e9232ae0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fcbd81c89898f19972098c31ff8091bf9e7f09d"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "ef3e79c8fb39a773f246358382b4a9b907072e8f0e08f0a4f018ec5f3ec5f42f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "08c7390967f014cc0d8227a0ed952540c3d3bca7"
llvm_version = "20.asserts"
os = "freebsd"

    [[Clang.download]]
    sha256 = "af37be5c83420f0b3906141f507c5679c699e940119016274b50fbcbfadcfc25"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.aarch64-unknown-freebsd-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a817edb3ee16b0fa517cb84c2328eb6b395b6b3"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "0429f089fe0c5f5a2e18c0c5903e47795fcb8a3a4153d88108b26b7026ab77de"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75ba47ec214e0027c4c6ab035a715acea762f046"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "38c74d983b96f0d5f5d857a5a5496f9a312a75e659e4aea6e163f6e7eb1aa31d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78e83eab13899f33eda21cfcdaf2cb34b58ecc97"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "4b255442eaedddede00fe30a7751dc7e02a77b287d07a8cacb3d770e359d9de0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf29fe1b62cbfe0e935d5ed5327f0ee9428baa5b"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "f4be5bbfdc49b0cf9474af7c5a17f4927f415605b818e985f31e1db241539aa0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3baaf57d9050457b9d50bcbe5a03e8c5699ee962"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "a1cdbcca66a0afe42fbfd2ee8e307e5acce0e38d9fce096ed1aa4c996eb3a1c0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.i686-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8f37297fc5e3785b8b7c059c0441b09fe0970fd"
llvm_version = "20.asserts"
os = "windows"

    [[Clang.download]]
    sha256 = "f32127c7b949b8b58a8531d5afce768e0272197af4597801a67bc6556204a3bf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.i686-w64-mingw32-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c640a7f69fe6d0fa80773043a0b77fe450b318a0"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "17d5d34d744948848469e05112bfe35bb82c3f4f5ff3ca7900ff3ce365f2fc45"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "410f2c69eab1f0335fe452923c1479b7fed7d9a0"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "fcb66d8a4031c451bd3c69d49681cd4f0d6a3d4d0706b65b17c3041865d4a2b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.riscv64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "42392c9f7689d651384ec0db32730f189a2d184a"
llvm_version = "20.asserts"
os = "macos"

    [[Clang.download]]
    sha256 = "747585fc19b6f7f3892934ca40579dd4fe3f4772ced3f87b35d312318d468bde"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-apple-darwin-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39d52901b14afa9f7abfc3859afa4a4dcc8e121c"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "10c18b40de95af69408b27fa6d2b1afbe4888182eef404f7dbab34a7b35447bb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39d52901b14afa9f7abfc3859afa4a4dcc8e121c"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"
sanitize = "memory"

    [[Clang.download]]
    sha256 = "10c18b40de95af69408b27fa6d2b1afbe4888182eef404f7dbab34a7b35447bb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87f0f57ea6595325a847bb3d8c120d4b48e3ccf5"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "b7a030c962be7f0d32f886e6a862ab7baabd05e4a04730fd274fcea3886708d3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "f476f8484febaeb6c0f85d946b6f619bc17b3fda"
llvm_version = "20.asserts"
os = "freebsd"

    [[Clang.download]]
    sha256 = "54f2b2b3c8ae30153efa4ca5df7aa68adb860825416486f4b57c721bd998873e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-unknown-freebsd-llvm_version+20.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf352f19a2226bf6f82b4ed17e8f3c8d3495aecf"
llvm_version = "20.asserts"
os = "windows"

    [[Clang.download]]
    sha256 = "b8713a7104f585a7ce549d30f1ae65e44dd4378c154b19269f98e970f8debccd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v20.1.8+1/Clang.v20.1.8.x86_64-w64-mingw32-cxx11-llvm_version+20.asserts.tar.gz"
