[[Clang]]
arch = "aarch64"
git-tree-sha1 = "9d36cf6adba8d0349344edbab52358eda9cf12f7"
llvm_version = "23"
os = "macos"

    [[Clang.download]]
    sha256 = "322af81d3637ca31f8d8a92d6a78905a3a197b7db5187705952e90d46fd9009a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-apple-darwin-llvm_version+23.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88354d3cf1ee67454e0fa24cb4c2657db92f2ad1"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "a6d4754bb00f3b815bb1cc8d8a5e7fa7789c87062f5b7dc18935a70ec2d14e71"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95cb6e9059a067467cf42539b05e2279791de430"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "e822f3d546a591ddb3444423193224f70293e53780b0396035dd4e59c572456d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-linux-musl-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "ee679531896da5fbaeb99aca23ee6c1e3b7f90e2"
llvm_version = "23"
os = "freebsd"

    [[Clang.download]]
    sha256 = "bd207a6dc047a051e9e12518ad1759e4fcea00e1bcc13260d17bcae04ccfa7d4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-unknown-freebsd-llvm_version+23.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "044d7e706caba9ec19056132ccc0805533ece929"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "61705e113ca49c9ad0da65b7b501ec008440b7f7e3530b3a86489b14f8532f72"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv6l-linux-gnueabihf-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e48444a15dc728baac9daf242d6eb359e76f2c1b"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "33a3cd8335a94cc700a4bf6d6407aa174ecc463cf17048c2303550e6186bf74b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv6l-linux-musleabihf-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "795a5c097fd419eb3e72915f3f2410591afb421a"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "13007c1e3d40e7a0aea67712a01dd5ff45bd2c94824e119cb08b3e71b30e4f68"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv7l-linux-gnueabihf-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d13ac3ec44a851a8f7c985e55cd63b8d80dabb71"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "32e98515307bdd53761d2d003365372dc0e26b2231c649b323271965c0ade686"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv7l-linux-musleabihf-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c239e1e5f5085751d57bf606ea562129156598d"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "2aa10a19349913206f8d81907db642d34a5db893310f853c29e66478ea144803"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.i686-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e84b840144e005f4956fa58770427707cb59ff3c"
llvm_version = "23"
os = "windows"

    [[Clang.download]]
    sha256 = "36f572af3a0399fd8f5467522b7a8253d92e52abc9266f451e2bd0132be31f61"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.i686-w64-mingw32-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc708b5b31ba351d1e49185de9234f53b0593050"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "78e3c069bb8b4d4ce3c514ab843ef610aab1ae7e2670e45b5b5eea58a90b746c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.powerpc64le-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "453d118f68501791fe7e884018ff8cdb3ad3986c"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "0ea917b6f01635a948dafbc5fe51ad44f169898431d7bffbfe42c180d185061d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.riscv64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "a21a8a5c81b674e5a73a16efe740c091102f6e46"
llvm_version = "23"
os = "macos"

    [[Clang.download]]
    sha256 = "699078d7af052099d0ab82d415789b8d7e3d7f4bdf2fba718e434acaeecc58a7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-apple-darwin-llvm_version+23.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd0c0f21ded86a94fbe4981dedf70e4ee194692a"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "c84745f868741d1b09f5e3e7d260b7ee5aa8abae70f8ebe6a47aed3696788614"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd0c0f21ded86a94fbe4981dedf70e4ee194692a"
libc = "glibc"
llvm_version = "23"
os = "linux"
sanitize = "memory"

    [[Clang.download]]
    sha256 = "c84745f868741d1b09f5e3e7d260b7ee5aa8abae70f8ebe6a47aed3696788614"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+23.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "310237c3aff960abea96cd55f1fb0f5c08ce205b"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[Clang.download]]
    sha256 = "f8456aa39319d403edf3d5517000c51b4a7cd63c951a9b30237bf29fc8a86508"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-linux-musl-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "21239af9f8b93f6b219a1cb535eec1aab922cb12"
llvm_version = "23"
os = "freebsd"

    [[Clang.download]]
    sha256 = "c63e5e8bf63c0ff3c9330b0a5c5748cbb9e01718ee89013d9dfe8879cb767cfa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-unknown-freebsd-llvm_version+23.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9402a2c79e447e73f510ec37d4324991b1a482d"
llvm_version = "23"
os = "windows"

    [[Clang.download]]
    sha256 = "c7aa5555826ef69cca2afdc1c0a4475607771ceddc75a28d8a0707dd348e83be"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-w64-mingw32-cxx11-llvm_version+23.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "a5766d220db8fa08c657f9a3b418837ba103b1fc"
llvm_version = "23.asserts"
os = "macos"

    [[Clang.download]]
    sha256 = "65c1e12b9c63839494ebf2ab7d68343686ca519e81829cb58f53173108dd64bc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-apple-darwin-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61b4dc2820d4e3fefa89578c5d68567a1b54116e"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "1b3d7b616575bca57a6de3c3ac166861c9211665f0d96ea6659e652e81cbe718"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27268378ff01647d52a3196ee9181b5d69086356"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "de50e52d03dc9359b9f97a389f754954dc70b2570351820e3f0a9a7c0ca44ccc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-linux-musl-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "aarch64"
git-tree-sha1 = "7d5512580ba79640109fed0dfcc4683997b2a673"
llvm_version = "23.asserts"
os = "freebsd"

    [[Clang.download]]
    sha256 = "5ef8ab790e559a4ed6ee455ac13d6249e61bbf4c21ef240fefa75c8450f5927d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.aarch64-unknown-freebsd-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "148923958029189ed55a3a3f73a1f1df6b33b202"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "fa7216618862e77f137f207dc3167f6a627f70fba4e1424be1bbe649d8a4ed5a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv6l-linux-gnueabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bd6d37b2e2fde88471bc39c51d6e85550e95979"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "cb7c6bb3072945225211c6c4719d9e1487403ba657a49424af70db80a43b0b5d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv6l-linux-musleabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1589db418b439a2d8300e103c8ed919400dc7122"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "6274fe8e28de8135f9d3c358502e353e2187fd37d9004c37a821607157030d1a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv7l-linux-gnueabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8654479002491b67c802cd82a74483074ade547"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "17514e2dfd0f4f43ea5ff648c3f271009a3dad6c29701d67e1a4bbaf154a89e1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.armv7l-linux-musleabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61ed306d2b46a5956b3e5e1e3bb7cef77fdd1374"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "dc8eb9e88e48b014b2dc8ec0a0975896a0e206d00a4be763483619659454976e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.i686-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f162db82fffa0035c2aa596af6446717fd0b126"
llvm_version = "23.asserts"
os = "windows"

    [[Clang.download]]
    sha256 = "c2427fbd3acc4033e8c58f06727e83df44af6d81b38454527d1b9e9693946ca2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.i686-w64-mingw32-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47c4bfe82228dae354c40de2b0c0d64e90dda24c"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "86f61d9cbc71e2211a90e043b8058aaa915954c076e734422fd5b01b8b8040ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.powerpc64le-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ad76cd7f05afd249107d7645c4b1eb552c83de4"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "900e29c9c39b1bb3342fd6e7643d1457ff86a6487129c7ea1c8659f5ab982069"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.riscv64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "35f6d77fbfcd3d9926647aee900e209cc1fde2bd"
llvm_version = "23.asserts"
os = "macos"

    [[Clang.download]]
    sha256 = "e386a6e5f198cada712d6fb14484d1c1ee6d2c15964ccc1d48adf69abd832dab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-apple-darwin-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc82705db785ad0122307fb357e07933b1a66ef9"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "5af04a32492d3c4d94217a3c209c4782387db54d3aaec867e60a8a15c5a522dc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc82705db785ad0122307fb357e07933b1a66ef9"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"
sanitize = "memory"

    [[Clang.download]]
    sha256 = "5af04a32492d3c4d94217a3c209c4782387db54d3aaec867e60a8a15c5a522dc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edbc8e353793705fd6497f3c17e5aeb7b10d192a"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[Clang.download]]
    sha256 = "b33399e28977f9acfed6961787893e9030175dd894c2c7230a4d7b230e64cb38"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-linux-musl-cxx11-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "6040fc66c9e33221a223dfef5b2a2ba2eb689572"
llvm_version = "23.asserts"
os = "freebsd"

    [[Clang.download]]
    sha256 = "fa1ae63c3926550974cb8e35670bbaa174e6efcaf2b0673a211e5829e908d269"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-unknown-freebsd-llvm_version+23.asserts.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "115e92ed32a1dc19f42ca024b453dcf65a578129"
llvm_version = "23.asserts"
os = "windows"

    [[Clang.download]]
    sha256 = "5db567fc5badc64e4dbfe1b073bca9ad24200902109cf835df8cea9929f921fc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v23.1.1+2/Clang.v23.1.1.x86_64-w64-mingw32-cxx11-llvm_version+23.asserts.tar.gz"
