[[Clang]]
arch = "aarch64"
git-tree-sha1 = "b3eb91787ac1dd24a72cda84381d43807d264492"
os = "macos"

    [[Clang.download]]
    sha256 = "db4f5623715a37d331774ee39ee93d275538422904ed1fe0f8a22202253c36d3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ae8a6a6445a849c7fae6e271bb6c26ca35c046d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "13c6bb70f86cf2d1622b55fa12d7f30a9112b50d65c3511a48e4a98f304269a5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e83a80b40fd2062bf3c8c743cc7895b506d5437"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2f6fc592d9e2c7c08e4b0123e21a5020a004738f82516a5c107808c8ea0edc98"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9134979cd9f11f57246d606f80a8e5061382ccb8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4663251f51b3c133e68e87a753e33d9dcfca9857ec2334726edc570758fd98aa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0895ea8a7452dfc99ce7440e99fc52adeaa761ae"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "600c3bcf7fde603b6fb76cbb86e1b5bd7fa3b547c6dda484405c1de38693116a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d4a6ca035d7595825dc13306082d001da20168d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "492c5e7a99572f4dea06c4d1a75af3b20b00adb4a14c08b8bdd71eac857594eb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f63961f69fd318e39b84aa4ca477ebf2647c6b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "71385e80dd9510f0b766cd6c505e8d5ffdd8bd170b0ff11e7c504e74d1d4b956"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a087f4262ddf6954e8730100bc533f2baa81a40"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "78dc90c761b9eaadeb9025863d8ec695d13bb3a96afb221e234d0111c7128b9f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f658fbbff6e8afeb29a4bb41ab7c8a65505b23f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2e14357b5e8a598119865e3ff7d0a7f4bf93f2a7c4231a9914ac5d29add58fd8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56b448d025b9145c91f21406127c2fa050758081"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "759e49133d52a38e77854deed63aa1050ed0dc9b458b95f6780b508b0c6e258b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01462118da5af89e9bec97b6c93a4486b0b303c"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "d0ef7f673d90073ccba28ab788b2d2e063f3a6bdc1939a6b199edeec7ff93adf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c55a1f91db07dbd7849ebbb123495b5b929c93f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2a27cdbfb67127e292f50194a8152ff0da9872286fb224dd3fb5b60538b9a9ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c48f93b3d323a72922eaaa36417e725811392e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6ea6f98449853fc43b7e1a4b9998527c320fd100b853c6fc775d8fd781eb5d45"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788013831bc029ecb96aa4f19579c2fc085c74ed"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9381bfcf02244d9245cc26758c72f87d5f06034a72d0568c774fcd54b4ffad8c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18839b2869972f36a40545c74fb72c3c4addc0eb"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b7c9acf90bfc07e5e377dbe723f3cf624441db06c05eed106484deda69828eff"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0e70909d504365e2b70f68d64919d2151d479c7"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "01852495c37e69ec4c1a4f77b6a036ae3fc678ab8e3adbecb9232855a9c9f0fc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe5e47c22efd5029dd74cef9041654b471eecd64"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "bf62699d3f51f786cb42ee475a54a5de2f3dc42ef11b433ab4adb87b7c782b96"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de67bf76f8af856abfcf51be05cb294154e1a7c0"
os = "windows"

    [[Clang.download]]
    sha256 = "ce2a8c78d12bb6bcc459759ee85ee953c332637a82fd7443afdcb87b8294ffd0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2870445d0c4c761ccfe7373dfa67e6ac14ef1def"
os = "windows"

    [[Clang.download]]
    sha256 = "e29d8d70af4e795baf81042a9ea1c1f75f88fc02fc63f0ef7ae72539a32fb4f4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1dda18226dbea8a9656b19c1508ba579c7e5a59"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "7621a1e91b177f6eecc64098f3754cb78aa767ee9c801a3a6fa29a8070013b12"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1dd7da41381eb0f2ecae21a0beb1186e8345010"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2d827211644b3027f497d246b55b7df5daebb7c42541f365c5cdaba8c8ae115d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "e53e0708536d4f467c5e2a48d4f665e57581f598"
os = "macos"

    [[Clang.download]]
    sha256 = "78801318eb67517a96863e65b3a7e36bffbcd862f57df1ee8e9c5d137a3c7ae9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd41f6688856bc6cc320cc6429af2deca544a32"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ecd74c5810c1055d2e8c7d1cc3e40cd35c7f74cd94399ba220956057f1d62f06"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8676d447ac19c510b147ae120378d2f57729b153"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3ea11707636f1ed661997942815b45713810dbce2b5d0cb0ba2491899fda9d5b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "883fa609cc671c23da59a8279bfc0a13f1160dd5"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "41bbe5ec5f67f870c4de5ebee0dd10069a0cff263546c6aadc46380b5ae0d427"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf1e24794e8c106d1029ac06c0c1a6960310cb2"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4a56090bf9254c9da120fd330dc40561e281519f4dd3c8fbc168b979d5386e42"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ae505dd4cfdc8b8b6be8280c2419e3da7fc46680"
os = "freebsd"

    [[Clang.download]]
    sha256 = "566bbce7459a0fe6d204cd870566a5ec222f0ef22f1c685275abe10c44cf739e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "083321defc26118da5ba999b97fd0f5c5b7d0dc4"
os = "windows"

    [[Clang.download]]
    sha256 = "4d5fc25c9217723ecde41d59759bb2902adef65c4ba0b72f7afefdd05ce1ca77"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32a28c5a2ba0a3e4603bc7a4d2e913b92dc0c2b3"
os = "windows"

    [[Clang.download]]
    sha256 = "15a96b4fcec563b0d2b9bc06b5bfb9a571d755d89bf5880d507b976438a7f960"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+4/Clang.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
