[[Clang]]
arch = "aarch64"
git-tree-sha1 = "9f728d2cf1d7629cf58e64f4a1b5818fe50bb845"
os = "macos"

    [[Clang.download]]
    sha256 = "36884d8869a2e54cf57945d525d1ebd6e1275d5e4ef9675a6c9c8d43b1e574ad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6596acab076742f28e02f42086abc2e4ebc38420"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5252a597441645e60b4bc81e1eb9fa4832ede1a380022ef4be67f64e23a64ca5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "630101c95ec1a5b7d197d133bf13f009c23c0e5d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9eb8a018c96d1d6268ce0f2f0699a3e7772b58c0a5045ee061658cceefdc8312"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b784485325a35a4d8bf4fee650cbab7fac6aab1f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "1e86474c003b166d75ffb94c7076d7d69e8c8bb8a74b93029d1b75d046b5c246"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d23bd50edeaac6171dd9443f0472710e3d0f51d8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "057ff989932549b877ac8110bc5718663d70d29f2d6e551e2613385d5b00dc0f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f7f685ad7e9561c39d55f628349108178fd50f0"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3e84e759e09c394a60dcad66dbbfe62f449c1190185871a9c406fd5f68778815"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6f9f58a6a4e1a3bc7c2f2f59c7c32108b5bcf45"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "39c5eb4c9aa36d9265afa86095c2f38a4c66748f2a8ff0692d04622249322897"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81a780162957d9de130f50c0259d4bbd1468ee80"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8b65113f5414a54c6057516465507fe7926f76749060f4fc3ff4229f42b1ceed"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca9e2fbfbc4734a0e6c427c5714f16009680fba8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "01e2f3f0b6c3d52732c08f0c392b203271eac0b2e4d13b84baa28c52834dc804"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb2b349964d98b82357ebdcbcdfc37cd12bbe947"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9807fd312b2c400bcc5df65a3f2972b2bbf2f6cf362358297e4c1e4f1f246b87"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e6ff2a4ed620b47c0e3c6b7e6fc95ac2279a53a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "21e49be4ea899882dc34e327b3cf142232afb16f6ff337df2ebb3bb758e9bec3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3470692c627c3abb3836428c6415abe7cc36b06c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "7a4600ce7e627aa9fcb9887b07ca9bd454dd6333a2f3366554b0f8b086cd0557"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12e8c3b4994e7701a7542b99dbff63f44e08539c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9b7c27260dc03fa1db6a87257a6c33eaa60ebcfbcc682f66a7bb35b06d00da16"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd91828ad56eeddee1176e376b7c79672d8bb53f"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "04173caa0c8da07f92de4c9d1c1bbbdcc122b233f0c5782f4c4709b17b07c9f4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de2b4cfe1f4e4921d29996595eb16b6a59f8f65"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "56018b08cf601e70c2ad60520f2336a7a8acd9b9fd67497bcb3a005647ce6733"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa1ea1daa1c20dd39c7725b835310cb77d5c8b5c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "da0dc77d728e3984107bdfe2081e25d75895175d8c24f1d602ad4e66c4537576"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e42e657e9667b362927243689dad7d8ee5b0afb2"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9af87dbf163229887d67e865989163c9782d5aba245fe6ef6a08f7490a736403"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe8d7a11b5d253a944b5c32f6c06bedd198f7901"
os = "windows"

    [[Clang.download]]
    sha256 = "6986793e42c942d69367851a844b7ddd27c3bd4824e7efcad1cd1222f4b62645"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bb6e7c00aa2bc19d61bcc4cb60eaaad2b3ce266"
os = "windows"

    [[Clang.download]]
    sha256 = "de3db096b79bf24ba81cbc09ee8b787faa163a9ee1a4d512f5aff6563d9d439c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6f6f0a5db8c85a8d00e565bd782023efc648c95"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "40a1f4280765b11c3f42399ac3963b2993553a94490af52e597098dd5e4d68d6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6151e025dc66234b34b3672dd1e7beaf438bb86b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a83af760bfc3e603aa0f3f1b5da6aebb332b73751c78fb1182a1facff6079a4d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "2492dd490806dbe2cb4c8c59c53f6616a5c1384a"
os = "macos"

    [[Clang.download]]
    sha256 = "07e2b0ac7ae2cf7e1b8874d929910c4a9bf3999716644ca627615c845bac5b32"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c0d2796c7bd7663466c0ac4e11f52c23917cdbc"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "0066df00659fc02890c8217f2294a6d95e676bf765d99e34df0da1e5ead904e0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d93aadd66f44fae7bdfd38d89981313ea1ed862"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "97e5b3c150476cd518b2a2516d88f551d1827650235122867495c08d5fa57074"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd2eea664ee76ec98cc497ba0f9dc38ccb8cb1da"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "1c378fa83600e0d7a1f26799327909db73d15332f0729a384c05c57a55e57ac8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "166620a1b4713af6711d29881e21446f4595de5c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "1c6f88a99e37805f3d800ee7e5a322d04b794ba791be41d4a5dc512c3a54781b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "2d8a4cf0d77eb600337d22422632a2144570bbd8"
os = "freebsd"

    [[Clang.download]]
    sha256 = "45c40b752ca43d8e4ace8dfc536478cd5ea7be92f4656c61cf0ede35025e04c4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27955c2a7932a8c89f067f5a8905cb33165e274d"
os = "windows"

    [[Clang.download]]
    sha256 = "157978d32e30d9d24aa51bf7f8a5ea70a911fb3202bfb2bc245f70d58ba6c179"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b33e5ad46dd3820c2323bbd2e98318491237e5d"
os = "windows"

    [[Clang.download]]
    sha256 = "cbe3d497ecf9a8b327498a81de1869054de048aa76a4fd24f7564ef636e21151"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+3/Clang.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
