[[Clang]]
arch = "aarch64"
git-tree-sha1 = "8fedc8e58a0df2b2ea1fbb597576b0b977d9eff8"
os = "macos"

    [[Clang.download]]
    sha256 = "0eb28d7eba36f0dd5d356bf0f5cbb19d7668594a4e11dae96c02665f3c915968"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5552bed9ccb031074e380577ee7e90172a0e033f"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "4c25ae5adaf96279f9952594780f5ce6952605611077dcdac073c549db71eb6a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2853f5b2ebc6b9685692b4ec01ebe9e634b137b4"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "fede4859007c627b303d855e9cd0eb6a0b665d6eab008594aaf897ae3819a3d4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "341564f4e8b2f47b95020ce59c8feace2e369a26"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "7b59984e67735a56e1af0b2f22046ebbe743cd635138a85dbdc41317eea77f65"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1b482bd20b9a0e1af2f36283e21d6d1c1003c3e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "e294a4db2c744ce2f0a1231c837a6b2eb03005d31422a97b264af38606accbfc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b8af439093bdcf3a15c6f2f2bbd6d996bb7a8b4"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "967a76cb888f3f94b50569429e4b4ac4a421f636da2b720de7ef2411602c975e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed4ddfd89179375f1a881fe02619727933de7ee8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "19c9c17a12064fc0184ee608f92f5d9da144a81380ca6c0f84419a957e05f622"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ad23abe3476761acf45c31103534e64087fa32f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "1b96e78846a021d3dba5101a2a3af2914f028f2b51aab9d127b9de3c4ac11cad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77f6e3d2bbf6e9f7971f8432607b874cf4740282"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "aa6920c297962397238451e39b476e8937ff8374bbe020035fce08dcc9cb86b3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db381e836c031ab7aa45be3fd1dca80238508c98"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c0183d73e004c2f8daa88c3fecdd675a1bfdbd1d36a6188a4f9ff2cdbcd6956b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d5ac94595702ed09634f2dcb4ba33daea7276b0"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9486660b4dca981376a9fcaf8e43063d24f535b927c1815b6216132800ca81e9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e10fc22048b52167dff1b094f84a024cdd95f468"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4210319f67e3e0100408c6834ee914e65843da60968e20f6881662562747a5d9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a69014a2e09908de085490654b22b15e4e7b4200"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6c3ce26152e129f8434204e78081f48fd7d150dd10d3bc2da83a2a2351541952"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f58a2c66e7c37658e1b8f1fc8f06674fc5d206d8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "10d46a8af55d3c1f94995f66b29a235594c91f58a8a3d3a9b0c352d641b4b2fd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3ac123ac0b897e8b1b329da64c93bb3a4136f46"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "fa52727792125a51c16131cb5168a65b7a1391fb3516633b7771d543ad27daa9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d52f05f4d176aa17ec1435faa6844762f96e261"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9f48958d26e0d0a734c905e928db4dd7359d6da81bb345b002265187b86fc693"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e150ff1a056c64e34a1f5cc596d7dfae62bc391c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "01ace31a8580d4d19c5787fc15b44911f407e44d3b8cf74c3ccd03e52340e5c6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f8b4c284cbea719bd423426457b20ed819c9211"
os = "windows"

    [[Clang.download]]
    sha256 = "29832d550f278d72ef2b3e563b24444608d4f04f3318cbb080b65e4d59513b71"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f24e49715cf5e1703803c1a3bf737b8c62d0af9"
os = "windows"

    [[Clang.download]]
    sha256 = "ec6a2abbf86a0703eeca46e27bb7a61de8b02d246e672a6ab6c34d0f25cdae53"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "243bfae17207144c4535eb3c77f2ba9021038334"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "d923f297892f7f934a44711a6fd8ce5a0ad9f5c36ae4641cedd5a401183dc0df"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb805f40bff4c60554da2b07839378cf03f9fb09"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "4dd267f84ac70c474f0bfcc3bd52f8030aecbdff92b1077de6859e1f4bdac2b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "b9b31fb31e630f59040a936aeadef8f5e432024b"
os = "macos"

    [[Clang.download]]
    sha256 = "117cf1df020f86fac2c276394d81df3c3b4f36587fc7eeed803fecf27d4c8811"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "337e9bf65a8bf899c084dcb068aa2e6ec615e5c0"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "807fe8abb70d6f65ef003bcc0ef077542fe7d0759a64bae57074987e873268c4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac1ece06a90994b85129ae63f278b48fc85a422a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "510f08759738f2d6acbb0b79ec07b6f0030b37d6018e470a7036d597106710ea"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61e9e0e9e1c44e3e2d192a3f5563fd28db3f3982"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "291b2f94f4cdda77cead4a63160637f996cc009b91e6e3dc466547115a5390a6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33fb55c930132f3ded00db30bfb5a6e723d34ce0"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5946d216d91fa232a724deb334740180cb8e3ea439d1c7873c09819b8ea74832"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "af2bb1fe4546e57eec1e52d944e103e2766ce618"
os = "freebsd"

    [[Clang.download]]
    sha256 = "124ad340ec1c01c21649a4b9d0b1ce8aa4427cc7d7a6d0a9a0ff4c5d9a6a446a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9e23ecdc87445081a887b439b7d8fe72aec2961"
os = "windows"

    [[Clang.download]]
    sha256 = "974a16e2e4951e1e512fffc114ccd7fea0fcf2ab28053bd74b3fde85e396b410"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e696fd77edd2f67bb645fbae295a803ff1b45aba"
os = "windows"

    [[Clang.download]]
    sha256 = "37e24cd3bb7ad2f97cf3dc988b7f40cd5d91ea07e0f60c677418f0b65d7be42b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+2/Clang.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
