[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa610c2168647a81c0f6aa3c0440debf6f6d36c7"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "45a09b3df81b77ef0a0c508fcd4f057fb0600c2cbb92b13cc7263058c023b366"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "844f0d9c0e219646e1a0f4960a4c48eb93b0e1a6"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "85e6288186be99dd8a6a46ebb478963b2af4a61f8f0159d1b9fb514f595f852a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a34a826c57d701db9ee5d0ff7978b3e289761fe1"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d847652668816715beb71357fadd338b0d995043e043d5c714c53676bca716f3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bbc2ac8ae4fd33c61e64f4868cd6f395cb5bbf9"
os = "windows"

    [[Clang.download]]
    sha256 = "6194354dc475e1790b52770893ffc00018cbff7c19e3fd2a190d22a78eac6799"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1de3b666d038797a2c89f58911941b8a60d7fb9d"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a7c6e5c8ef23f0d57238ef26a89889bec6d860efa7ddb0bdcd0b2d0b57cef8d8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1037b5729810e5cf9ff86117f110e5d7f6548bb3"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ef906757702ffbdf40cdf2320587057f4b8668638464644cc78b0c9e614a0af1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b9323ee42ba93ea79c6be32c59c3f21e279fe36"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5a71832170fd77018d07a72e4a2ea0d1237aee04c85db00397e87035984d06a7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b91793f0eec09608d7dd9305af15e01b7376e77"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8d9a62842ffd99acf75f80dee3816c5055b4f687560c687b0fb82449dbe97d3e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf45bab10d02a141136041b08181309baaab90af"
os = "macos"

    [[Clang.download]]
    sha256 = "d75abd72f75e7830cca5bbb78479ac69b946e3217d21ab1c6792a1f08ad82cab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "297ebe53265b18853342b80b7e1dadc5259e6539"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e806b47c58c32ea891874cbe41a4b38270bb9cc8cd5dd8cd4c299c836e525eef"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd94ae64f2a83af3c9401101cb47b03d623139fa"
os = "windows"

    [[Clang.download]]
    sha256 = "878d4bc02551a78ff15bf4e9ed78322c2f5318b400ff61d0f465c7570487da9e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfa49a6114e33213ac2f640fdf99cd126aa54762"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "efb88adbde4cd30db3fb98e769d33c7c60cbae03beac3612a19417ba27733536"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59aab663b7708187f54278afbe17dfb46d668a28"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3de1aaf925506c8624490684506739949590760d670c66dcf0a5b17e9e932b2b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "839615dff7d9ec8711056a29b6bd2831a866a934"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e45ed30be3b94c938ba2b700fcc4fc617344f36cca153b3dccaa0d2ba9fb97f7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "758319771dc5ee2e1d54e8eec94da93065f86819"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "0bea9bda27d580427bac5502e6db8a2fa48012fee9ce0668f93dba7332682c8a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf45bab10d02a141136041b08181309baaab90af"
os = "macos"

    [[Clang.download]]
    sha256 = "f245674d6b4467dac7ac98f66f898330eee3b4dd4e24a1c8d03265fb4b0dded3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e54725d55063e32e13559953da754ad1241d9688"
os = "freebsd"

    [[Clang.download]]
    sha256 = "1c8b6181b019a15780d0cd76fc54955f9b2ee6f096e87d721cc27d3c5b4765f0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8df85c2b84c4c1972f69feddfa8f110a98066097"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e5d0cb271b35405dc366297d40e2ab3a155964a3faf64bd8d279230afc012041"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be32d9c3a77ab4254799657df01a334d8ea885db"
os = "windows"

    [[Clang.download]]
    sha256 = "887a983737749972756e461a2bb2953dfc3245fe5ab2a9cee1d657c4a8aa9d76"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9fc991b4c3162508f7bb31595689ea0567d948a"
os = "windows"

    [[Clang.download]]
    sha256 = "f35c79b67c966d70673bcbcbf954be995f08cc95f90350d05b8a3b26202383fe"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e01cb982b7d8da88d19f348bd0ef232e322a89e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6f62559685165c9736f847ae9d7fa701b054f6582329b6d886be8a98e209a551"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d7b53a8bfee4fbaf8aeaa6326f074ebb9ac292b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f622f79b8fdd422dbbb2524a24f6e493669b811ec0c0a78df20c53e9ad760b82"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edc54933a5a463341379abbfbeb673540358bd2e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "393e5c513126685fc8f0897363f3c205bc0f0c9893ce00c37e88b98d861a23b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8be313a91a68f591bd27c0e56a7b99496506fe56"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b675c8da9759b689ef7738a2ef4cd2950cd49476091e0d305366245fe6a35370"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "114ecaca1db1d89497758bd9686ce3749856dff1"
os = "freebsd"

    [[Clang.download]]
    sha256 = "3fd4b3eb7686885bdd3f15d9e504c64ce21c6dbf63238703f999436b326901ca"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1b2c1787995ca0ce37c42cf3186f75a1c1a5e03"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b38ed0271f3b5de8e34358e7b95a8534a8d29086fb0b0da167c35bff7cf20d1b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+3/Clang.v9.0.1.i686-linux-musl-cxx03.tar.gz"
