[[Clang]]
arch = "aarch64"
git-tree-sha1 = "9b29b728257a2b6889cc6747e078cfe19d8cf5ff"
os = "macos"

    [[Clang.download]]
    sha256 = "f1e16b718da531add5932be466056f70a907d745ce67682494a978d7e52a2e25"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ae8a6a6445a849c7fae6e271bb6c26ca35c046d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "21af153180f0c19ca3f1cfd3b0ddb8fe17d919fe73f619effcf2c24d9e1cfbae"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e83a80b40fd2062bf3c8c743cc7895b506d5437"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "cdc48a17cb2753aeaf426588679e1f8d38d1e0a7104b21e70373dc7d08c446f0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9134979cd9f11f57246d606f80a8e5061382ccb8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8b7a0abdfef7aac68e73fe57bac4286c7db8380bdf90f407549b2f30f8e5f797"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0895ea8a7452dfc99ce7440e99fc52adeaa761ae"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d5f9647428fcbe1ab5bff52f156c8b0b42d94196363930be485892a78363dd9c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d4a6ca035d7595825dc13306082d001da20168d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ce8b4857c8020ed5a859abf9b161dbf244ece63257fd745d3f3f9015c3d714ae"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f63961f69fd318e39b84aa4ca477ebf2647c6b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "0379a22bdca8a6ede7e1dfee02c0a62b13f6777709e501442bb6f82113af0e2c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a087f4262ddf6954e8730100bc533f2baa81a40"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6129b9a287d67fa9f239f0d080a1b134ca857be0ebb2a3455dda10db1f55db8a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f658fbbff6e8afeb29a4bb41ab7c8a65505b23f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "10f3fff121e2a6a9815facf9c2c5e1742584385e9d6df5bdce5a310814e2fcdf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56b448d025b9145c91f21406127c2fa050758081"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "90da685729c7e5c6c80b2af17314977cc67efb68820d453f761dfbf7f9ab97ab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01462118da5af89e9bec97b6c93a4486b0b303c"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8d1fd2fbb466e02bfd617e0643d0f784639db9706f678d26d6899014dc74090f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c55a1f91db07dbd7849ebbb123495b5b929c93f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "619b72470282d191a9351f531be01632f8372e329a3d0a7640a9f7a2ab4c0d3c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c48f93b3d323a72922eaaa36417e725811392e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "205f119402b7cccf335989e6775fa5b262b31f4a22c72cb8f3cd05e79967bdc3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788013831bc029ecb96aa4f19579c2fc085c74ed"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "7efe3d91f2b933bfca66f5614f50255c30cb2b021bb07e00eed3dbfb6f764d60"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18839b2869972f36a40545c74fb72c3c4addc0eb"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ff15dcb055a82b8b82d55251f3b32431f4c1766258d07ed5687dfc805cd762cd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0e70909d504365e2b70f68d64919d2151d479c7"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "57f6cfd85495904c7e0f7a5b3a4cbe984d481c504b9dc5c21bd1688102ba044a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe5e47c22efd5029dd74cef9041654b471eecd64"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3131fa474961e68373d326bb777db296af3a7c5721ff43855fa395c493375436"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0920c476cff8c750b40a06f2f5e84a253c27cc2b"
os = "windows"

    [[Clang.download]]
    sha256 = "cfd4905d726cd80bc75651486ef84390688051d783eb12b1db984c2e2eb86c95"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ae8cd25faac53787507df63089f8840814db95b"
os = "windows"

    [[Clang.download]]
    sha256 = "27bd392fd6cb678519211b4f2b4bc0b665c98c9e2cd78648d646ff35a01f0ac7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1dda18226dbea8a9656b19c1508ba579c7e5a59"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "db4fbd691c6101fdd9225e362b34da28db9eac4d23eefc5bbd5522a2c3ebed10"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1dd7da41381eb0f2ecae21a0beb1186e8345010"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2e4becb4090afe378d433e56d186c63b6b92b29595a369c6acbd7a3532fdf227"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "63d6fed5a0a60d460df32de320ebdcdd4d55ab67"
os = "macos"

    [[Clang.download]]
    sha256 = "8e01e599ab0dda947cc3f1ca0b71e9c0c884be00df9de2267a6d1e7fa63ac82b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd41f6688856bc6cc320cc6429af2deca544a32"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8ea7f3a34e08593c6ad1096a7c1feab22e060ced3529de1fd00f43f7837b4afe"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8676d447ac19c510b147ae120378d2f57729b153"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "11448f3d3e44757f48fcc01ba9dc5c238218ffdebebbfee0d3bea2e615139376"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "883fa609cc671c23da59a8279bfc0a13f1160dd5"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a22fdc6557841cfcbf9ad3de0e4dfdbaa81a72ba4faaf42a142a7f46f13e441e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf1e24794e8c106d1029ac06c0c1a6960310cb2"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6fd706f91f69029e2b84228d3383091781cda66a108ab53115ae6eda9571fd8c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ae505dd4cfdc8b8b6be8280c2419e3da7fc46680"
os = "freebsd"

    [[Clang.download]]
    sha256 = "de34e4145db228a14362ccbd7f788d1ea0e4eb437596bd0c3bf8f7001b973c0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78c7994ce7b4127a76ec5617f78775b5119d242b"
os = "windows"

    [[Clang.download]]
    sha256 = "5de0552aa8d8adfd87dc9b49dfe024d30830d78632dd3a7e8732de4749029c1a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "136f374d6d38f832f83d1318b939a0cdf939a9ee"
os = "windows"

    [[Clang.download]]
    sha256 = "0a697d85fda8039e04d2a1529064151758a93247540e250320ceb00d86d06bb1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+1/Clang.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
