[[Clang]]
arch = "aarch64"
git-tree-sha1 = "425a71582560c020ead54ccce8f1fd33af1a295f"
os = "macos"

    [[Clang.download]]
    sha256 = "1b6ce7342730b0cfc32f6916da7754d0e9ed2ec6bb14167d4bb0a8dd734b0900"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ac6fae4ddf7e701718518eb40e6dec786551fdd"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ac0408dba6c2f0bbbc80d54eb20a6b66045f56310ccbde86c74156c635dbd747"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88d5ed91961557cb8a901ff584daf9348c59cbd3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "7856bdcde25c2daed16cff64a8742c1b7a7e5c543d9992b313dd491d60c10044"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3a38f21ba429def4aa9b7371543ee7cf8d2027c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9a1cdc28822fb82859ab7cebb37d4726d68c6e225d7f54133a6c6026e2a43c99"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1433a8bd511314ef6c1216ed16b290cd932e8247"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "f846c3fcd0259b7ac945e54c55b82132fb9f0fc08276a24b59b228c3b116b48f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03f3998b9a9b42933395bf881bb19119668a266d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "0c0aad82b3cc56ce9938114dfccb65521c06478e50751e5c8f06af22e0e7e439"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e9c2438ea6a037265b25f2185328ac9a3237ab7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ae500a2a01b5ce85d5a9e76fd7d32036e08e97ba69b207de106733d2e9e3448f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "463ea34b76adf765f25389cee46e522bbc99b86a"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "f62e43629d31d81adbd43141bdcd4a1509989944afffe8a2fedb45a663066b61"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f02c44b130bd9af9404670a422be310af4007937"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a137df241919c5c4a41219f9af5b6e329e3de46c4fe77f910962943d0cfdcef9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a07f13392f003a870bd7a9b138b25a088112a4c5"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "a6e52df13b726836a77fd767c061936df3e6578721fa7782ce7802882a656c40"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81b5ce0f4f9c7dc51c6097dcf142cb0c3bed4e29"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e850afc2cf5de3ff14939c49be61d4975be6d4cdb3d08c407d4c0a8ee784de5a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8a0d8ca8411047cf968978ecc4b4c618e599889"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "aeb8a6867f2568754e4f598a5611766ecd4f8d9b6d0c6c56d89047888589b60d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cca8dd6d42580f712c48c8f436e17ca4bdf3d39e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4291eee664e5da978a43caddac9128a5804d860e9da75f8931757a1210310932"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d28e723a73ea3d7193fde7eee3da9e75876e986e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "078ded3c3c21f07fee1f3a374f5b3e72b03015fbe3a8187790e9d6a647f0f201"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b905c2d11e46be666b3068674687ec56d093673"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "63ae7552ef31ef2a6fa48572200361e1a4736dabe4e5dba92d1cebaae0ca7d6a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4125bdac4643af4896bc3a73d1ba1b1230bcebbc"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9c5790c17d6191d2f569be1ee88fa42a842551a917ef1d9dacff882695e3f386"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83445b9fd4395695e960d88beba1cc3fa4b52b4b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2612ab2eac3f89fb842d22692887cd9107293e762c24970594ca5f49cf2c5883"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe13ba3b2c0dadcc28874a7954f05598c2c31182"
os = "windows"

    [[Clang.download]]
    sha256 = "a9fe39dc2be6dbdf327b439c090d498d9014288b79c8a3eddc608b0868bb6c23"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88968093309d11d2aff3fc70bd125fc707762a97"
os = "windows"

    [[Clang.download]]
    sha256 = "69d83b3808889006b244831b9339731b80c77e311db8afba1017c7937544406c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddcd63dda98eac97966d0450bf3d68a281ac71a9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "24d497e4bc8405837858d6d8264c11dda6246f6106e3f432bf4e174f45d327b3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2db205dfa1b439b82b477da1cd535a75d28ea805"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "282b3a339bbcced44006b62a0d9f45246da1e47306f806e4b55198d8b87dac6a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "923d4c8fc4d117618a56d56de73b8a1273f0c304"
os = "macos"

    [[Clang.download]]
    sha256 = "0a32d3867a65db0b367cb2b2c07c6260e552e3a3254c04e8c6d9ac835fb6937e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bf0229df933c70dae01885b9f80e07e2759de17"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "793ac27f7612992527a46714c0b365cba7f99194f39f98e4c7082c670c5e6ba5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31d12173811faded0202374707737afe6162bdaf"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "604f4f1631ab42373c9fe4fa8dff763dce1b74f22d32f499b8fcbf92743967ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eafd54fedfe79cc4cd76b65ef7af50226b6197d6"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8273a402d1b1e66325081bdf32fb6689a26d8fe536bf7cdb1794403ae9003d71"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42a922690ca0b97c071ff6216fd811038e3a3b80"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3bb7c7338af0a74e6d36dc405b82129af1414f947e740caaa817aa13b89404b3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "336b8d288500d9e5ba76cba562565f1c43b2e0d4"
os = "freebsd"

    [[Clang.download]]
    sha256 = "3139ba0883ddf698aa187ac9bbd39300278e3a3df19d80455eb1a5cded4d7f64"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b68f7326ed4d3b6555468bff088ed68119570b4c"
os = "windows"

    [[Clang.download]]
    sha256 = "7cfd265d994e61a30e724412f69b300bea99f5e2d75d3716903e40079b765448"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2de36757e4deeb50c126e685c565a4975a8f5331"
os = "windows"

    [[Clang.download]]
    sha256 = "4fbfd58861e3ad565b4dd93ab926cc92ede217dd90f5ee9c421f904e4911ad62"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v12.0.1+1/Clang.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
