[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b0fe9970d98a4f981d3c8139c26c1275bb87a8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5f32246146ebe16335e763073905af7e574189af5945e2dd8f0384f6f8aea2c0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4318f6c419b88aea54fc006ad4065872780d192a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "4f8efa03705d1c62bc6fa163fb6b531153d97516a1a4bb96c7a289c5bff56c77"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c1958baf7d33bf16e10fa96051d3d62dfe63ad8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3848d75b367e65af4e0acd57f4a6e56354ebe240142ae0741da79cb6a02ff7e4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "774d3b7127c9bddbdb84eecc63e03762630d05ad"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a8ecb260559e19eafe09ce562831dd7e1654bcb4f9999c52bd1b45dc147af660"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0eb78834672fb870f4b1ea48436b48308898f9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c3ec4db86e0eadbd7653a835f29cba81d6ccb38b045c1fcf27e5cf9b16eb3098"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fc3ff57692101a729211b7033bb4f22f07ae4a2"
os = "macos"

    [[Clang.download]]
    sha256 = "233437b067d3b37bde4b5da9f542ec745161925957297841500f6950f5bf36c4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9823d67b3964a723e78c6444df468857dec633d6"
os = "freebsd"

    [[Clang.download]]
    sha256 = "2dfb9c530075c827ce330875492e335b303631d4079b6a74548ad91bf8ce78f9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c16254c3373e9f8752795683645562d6a8e75f7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "bcc8d141008b44e98a33fcb18aa3ed8f8e6907652d8749d1ae5caf849c17a981"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b3446c80936628fc15704410a45338b14b8e965"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2e4730a4b218c0570f9587fd80ae49939789a37257c2b838381ea985d0f7da5c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "038fd29a2cba59e5dde4d6529ed8e37f19eed480"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "aff44263c8d98ce7792ffebd3d9943b34583d509a62f55565dff144ae038413e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df5e03d40bf19d8c3844a6a4fa3103d0c360251"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c504aef7363352ec29897209484daca0ea7431284bb49e21fba185cc3d45fec1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20840f498be7ed5f38b7607562533a8f9a312202"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "526d10d6fb84e5d4129c15ba246a1d579d92766602a60db563c72675a4be10c5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82135c23a2827e2414051a5977f0e048c1c55221"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "130c59f95f63c718aad116a2376aa56379813a12261487ad90d9d8bd1a16c53d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fc3ff57692101a729211b7033bb4f22f07ae4a2"
os = "macos"

    [[Clang.download]]
    sha256 = "e9c6851900c445edf2c977ba48c740b9cadcfc0e556a79da3bc4e255fec34052"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00ad9e8d81e99fe1c90625509e2c280c67b59bd8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "7de794099f556f4850236da3562a6d853566e1ba5dff986acf543fbe5cfebbba"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11d73871076a4b50369d4bf7066fdc65ed8be9f7"
os = "windows"

    [[Clang.download]]
    sha256 = "2f7725358d4cd77783b816c3fac57a0e0da4e34a9a45dd75bf46f0801a7f3b1c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "899e8791696e8e7bb2b561167fcb1748cd6ff0c9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b1fd6e2d03c78e933336c27a9ef1d6b92ffa03f6768bea7f26f647ff7e8aba7c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a006be925d7ef802d5ab986441736e92cdd36290"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "4f667a125dde43357d90840f819b057150e30fc8711a7367308316e38f660b76"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee45980e6fd489d8231b621ccb2d918a74c37324"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3962a560e8f14b550d7bc4fa6b81459ff91a3d56dae8e52b0f033e12924973af"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d03a2cbbce8104aac29c3291ce443c45054aa4c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "e35695c1caece102cfd82e46474c08ac33f0333b78860a9eed6eccd336de969f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4a3d31df91f66cd6bd9be6a88f7af08403a68a4"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "387d26166ae27070c3c229b4f77c0518e5fc3c45140b35f0b029abcf9d692146"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cccb99da8689598be090d7e0706b64d0d1bd5062"
os = "windows"

    [[Clang.download]]
    sha256 = "20a3d880559c90636d0c0189aeaa7e7998cd6492982feeacfe587aa9305cc2b4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1eb346b985d04da636f494443dc773bb3b1030c"
os = "windows"

    [[Clang.download]]
    sha256 = "f3277ac5651fa9b1a7f670331884eb09660f68bf5a0dfe1cd14679d355a52e06"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d22b052687f3443f702c8fe1110022e33d7105c2"
os = "windows"

    [[Clang.download]]
    sha256 = "e5fe34e5192f14e3ae98a485bd21a4db353d801774dfef9939874a415522bbe5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed67ed0dfe50d2ee018d4d135421af6cc209578b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b2032ee717e6b1cfebc86c639e034e149dd3cfe3fbac748452bc8c7a45f02323"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9823d67b3964a723e78c6444df468857dec633d6"
os = "freebsd"

    [[Clang.download]]
    sha256 = "8b5dd691ca91d45dd38dbab360bef7704d627fd58fa501dafbac6a02472048c0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
