[[Clang]]
arch = "aarch64"
git-tree-sha1 = "1af4fb7f9ea291ee62088508be99dcce1c2bd956"
os = "macos"

    [[Clang.download]]
    sha256 = "7134586f84987174666c0421abe70ec24f7503f6be2fca3f2efef1dad8d76029"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f33cd54da9ddba4d568dfa312c7a554269433305"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "52cdf8c6bef06d426955592c2bdd4407df2e78245b27614d60188229121db7ca"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eeff7adfbabe8b63574d118a7a95b101679fb69"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "24532729f7a0fe23cf329ea399dd0cd43dadc7d539279a3d3cf4aa8e7f9d389d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3feb30e6a798fbdecf101c0836115d69b6c5dc8e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ee8a614e35c9b7e180237ad33a15cf8398158c9a042b48223a16dade7a4fca9f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "032adf28d83a4eb169b581a7e29c95efc2dbdf58"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3c0f58295e8aa0e5264d34f7b381656216c5b4cd648c71170a0ed4def00dcb01"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c2e564fb5af6908ccd5a8e9371f2d29721c4a96"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8ff599d31b2e0635d224a270c5657dcd00d98b28cff05ab57d4497a6b9f07eb8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0da491c1e792694c8ddb2404e10a69856a35182d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3097b9413d80038b11f4515a1256e6097bb95cacc47a7271bf321c049ce9dfbd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f6cab590ce77ff504c72dc8262ddfee6f086c0"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "08ca4df46dcd11bb2383bdeafc4644d69c79cfd5a6ac36240062ec8c2c3629db"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee1af8ff123dcf02aa26e43f944cbe40d50a264a"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "63476fffcc4d1e3cd65b43c814af044361a345bb39376fbd4ee86f08332ce160"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75b79802aad15b23a37d106b73a2f923ada4e83e"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "505642d1e62edc81e442d0826b4610102f68f030168970bee65ff9a30df3a1b1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38e99dd94eccb8dbc897db0f0d0fca3fda861f96"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5960993a7b62b300d9cb8eacbe884ef329eae436af4e761cdfd2e6dc7454eac4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b886476bdfa9e72b8d42ae5ef5911cc58464624b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "93c63699403455f565b8aed4d7c255903df71cc9b099949031e0a35caa78b6cf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bb14f5b8bc7fbbbd2ef3cbacae9b6d4f8dfbf5c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8bb55741bb27b52a305e9cc5a22e340dd0ddcc780793b2de584a42470dfd1cd6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ce0c9613fb1686702084ae8bb094ec1c679a214"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f33122fabafc6a08921e1a6e881e1e645a17cd108bc596dacf8bb8909b78300e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11ecfbc76054742240b17a2c7f1b8c92fa601eb3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "92ce2780b56e3ca05fe752d66e847a9cc697bf081d92922ae86fefb9da30a4ee"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0411fc623f5cdc0727eef6d7210be0ec1c3a3722"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "77ecc68364cbb87f51f62ed3ff08512ccae2a0d2fa0a93850c806ad76b69cf96"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a91fc398c71f99443041a7a97d22b6cb75a599de"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "c2d543164761b0ed530c1bd0c324c050320aa9d84a7251997be8a0c83f76731c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77cdc90cd5fe8aec312d378f1eaeeeedffcbd5b6"
os = "windows"

    [[Clang.download]]
    sha256 = "1996f8218bf353b222f442be4c02d02d7921aef54c62ddb75ee36c843de9af6e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b8b89ea763fd7a4541e106f2e9cec34d449ad2b"
os = "windows"

    [[Clang.download]]
    sha256 = "e1cfbc9fefcc34137377ffdc2b1dad09fbba2a7d4028dd7b0e1dcd8ef1640db0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5002f8aba8ce7322ea1a90c3ed4ea2b411990b8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5c4db342d8a0e8127f02226ac9a674a2bca3e005100888d5b8b39b3ad50555c0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "262fc44f04029b2aee3df339ea636729ae64d213"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ad28dc1846d91c8ac3f0d303a3bf3ac30f5a869a327610bf65b1216cde498758"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "d72c1f10f0f13d13f206e4fd2bf7e0ee6a68a494"
os = "macos"

    [[Clang.download]]
    sha256 = "7094e18583a8e0e56dfe42a006293d0918530d78b1c7368c98fcc5ee1fc4f563"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6aeaa3caf6bf7d7da97113d403537b3a23ea451"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "02a3696c4d2091fb4d1e8b877827452f8bd1cc7689387b4fb8d98a9d7bccffe3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88dab3027140e5f49b87c98cdf19f51a90e85c85"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2108a1ac739e562011dac76e5962d13822c18f26e7df9fbc6479c7284f3648ee"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1a5ab43895f5a5c6d8b611f6dd01f3f01e03ac1"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "f96b29a8ac8470cf2c2ece7d463607828e70be386dca5bd8939465d977bdbe82"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b525a6a5c81c13415a208bc54a5871e0c79aaad4"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5437d81dd6d8385da79374c35fc6b93cdb57c0066e3587163c5cff23b8b8af63"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ef1c3cba28c7a2b66e2e75340994473ef9e81a44"
os = "freebsd"

    [[Clang.download]]
    sha256 = "a7978a929e41edc2233ef733b694f3de2356bd2fdc492271eb9dccc8b8c6ccbd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dbc13c3afdd83cc19a0044603c8e11bc3f0a71d"
os = "windows"

    [[Clang.download]]
    sha256 = "c63caa74cb8e3f559fbde1ee8cc1fa2de427e7212dec0fd27f9a725281c67b33"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a475967ae965f52bb13b669680c7bae0ee0a2df"
os = "windows"

    [[Clang.download]]
    sha256 = "f04f4bf5b76f96752a43f5c242f45d0b07faa04c247de9ce02d07dcb682fbf52"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.1+3/Clang.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
