[[Clang]]
arch = "aarch64"
git-tree-sha1 = "2ba43bfa7084d26791eab61c384cb74caf29a819"
os = "macos"

    [[Clang.download]]
    sha256 = "e72c0b54090b81d7cd4dbe9e99fc0761719dd7209362aef810c5e853316e71af"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a79903aa58cc4407c33360a96d128660aa2db642"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "805c1f09d8d41f6dabfefe84d2e46ed1d7cca6f9d5230e3ee4acb1bfac333bcf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "430cdaf796188d305c202b7791ae7bdd108c0bb4"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "858375eaef38be29690f9535a656e2d9b7ea21bb50024b1c336dff7460005cec"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cafbfa7eb8ad7d5cc483542a04ca2eb037573c30"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a6822e9087d6cdf96c28c75e028be603564ace5720694fff38623ebe4bfc96d1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "655d96569f63c5264174bf534fd37e673da9b9a5"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "092eaa393e54a160bbfd1a64989a95939382c3e6211b7cc5fdd8fedc93409d14"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c83301a09785efa3e20a054e4934931feda42f9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "6ae741abfabb1baeaa75b7043e3cbfeb4d3dda58ad0ed24fe324bd9199133e70"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3baf41e639d6d282a9ddd281e47ffedfcc8de615"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "00eef4e189eca1728f19cde4a378d41c7ed8f0e642c94173af8ae9c52dcb0312"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41d465620bd0a055468e2263fc6694cf8a6a6b00"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a47213f6c7bbd98535fdfb00356c7431564b54b9636ecc728396ae22c5bcbc9c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b76dc78697357379fcf18896af4d7577f8ec2581"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "2c0fc1450d6a7d20796c5dd99c3e5ef1d2a83336bc8f004c1e450eaf7a510345"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd0897e3c0b57ba8ea77337bda49b6eba891a9af"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3e5c8cbd66539d5dd2617e23f65c21d1cc8f20acb9ff0c8291dbe67966bd69ef"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ebcbf215d1982c46e3e3ff1825717ebd047c896"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "d5642046e326f23c9bc3765b18701319efced7311b9b9fc356e8335663a9ba8f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8446f201dcebf7ef222bc56769166b9a3b12b04a"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5921aae63c114e4e1c0a2c772a363a5e222a2b18afc08f381524b6c2c6a288a5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "654b0e969293349f6f60e06c93cf0323e0dc422e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d32f47d1fc02a433e899a5534256cdb11de47b19d9d1bc3a0ac5d48137555d03"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d194328546a39ff9f44492187806f40f0754b8a6"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e90211eea6c8d899b2c1d0ce05fb411ed2c1e338e19ca3a9644ca9858ea28fa7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7e7e77c7fbe032ea3e8d71132a321ccb7e80662"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "1ce33d9a9715f85297de8263c6e7f5d74a5a944db224e9a235f337953d364773"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92a8e629aa60be2a777d167ff1dceeada12c1977"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "134b8fc0bf670a6a317b42d75ca2cba3cd439b2a3d1d79b59b0ebd9baa4ffca8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45a3ec36000e4f14a56e8ddf8f2fa42789b1f0af"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "70140dcbb3181ed95f6423e5ad0497301c453e03e161e8a564bad3df71d8c3e7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "494f90bc5822ab5be1db0da4fab46d05ab2f30e8"
os = "windows"

    [[Clang.download]]
    sha256 = "c33a98052b9476f0bbcbd3bdb2d5b4bffcfa01d93be674efcc6596b650068a3b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "805fdb65e723a0af12a22f88178f516fd61d52e2"
os = "windows"

    [[Clang.download]]
    sha256 = "5ca1850048f72f834e748ffa2290800d7b62d050a2dd426681b15924d8925951"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1911a86fec3a9b5bf2d8a1a940e70f088ea0efc"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "96c9c67cfd8ee795a7798fe57431c160854a932edfdc9d6e143c1dce84a3bd6d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "540d0c929ea7b0e2648705151e6f090528c4e758"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "aaac94fed55628924b259e4eb5166dfd42309ba142c6a5fbde3e51680d9ec927"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ff2cf525eaad040964d807a666d2e0bc2d5ee309"
os = "macos"

    [[Clang.download]]
    sha256 = "3c625f983b27a2044396a76a24d5a4f6ff3663deb8a4a1126433fa8cf298ed16"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "babf848146e3ff61b3736d0b8e60d55a11c7fe4b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "48b9579adc454e90dca97a99a493fd434ea7abfaba1da72a3cc30a63dd0ac18e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7c8cd60ee4ea5e83da3a565f291d15ec7d3376b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "1a597bdbe7008f4ed62539db1672fd4ef88306b979b193cc8982099beb0747a9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57f3c4521f084bdb60ce92f43e25c7671fc39c03"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "fc38640b31b03956a9bc2b0bbad195d9d1b75845dce18788b3d8f8aa300dc038"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e25029ab27ff0d3b522c5a5f3dd842359fba650"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "57fd44bde33ebbfa69270c01a38fd6a371d3b4edf80ed1b80ac13d35a2a2b86e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "9cd9af516ee07d61b3c2088b1793fe3edba43fa7"
os = "freebsd"

    [[Clang.download]]
    sha256 = "8cbf50d6e74eab794c5b34ca5aede36a2be2b97537fe273e0735ed55fa931bbe"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28d3061d5b8f0a530145dd50c083c341011b7c3e"
os = "windows"

    [[Clang.download]]
    sha256 = "4953b413eb609a9afc9be994e5515dbf532f050fe72deba2af648de5a5036d9d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e78f99a2c82de5d5a91a2ae381cb2d54a5c67155"
os = "windows"

    [[Clang.download]]
    sha256 = "b268862f89d12443688abd2f575622c2a121e34efc566ce0f0c7967d1f32075e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+0/Clang.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
