[[Clang]]
arch = "aarch64"
git-tree-sha1 = "510f353243ff0b5cdc730fa140f4d185fecc4222"
os = "macos"

    [[Clang.download]]
    sha256 = "367b274d55848b68b723205d8b8a131067cfb7f9197c1668bdd5f41a14483ea9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b18149570965e53ced0a3edb98fe71d41e4a4ec"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2381c71300eb49c03ffcddda25f877f0c3006e31de802d6b296622e15938782d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3a6f9752c0518e0bfdb6dcde30b0ff6e05b5b97"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c2808b268981b1d57b2b04a4d5d89f9b060f6e753fb925fe3cf29c49dc9aabe3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbc109a8649cc47d0f50714255089e0888b35a5a"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "52ddec0a8824657a48d048006f302f68ce75e5158230170e9d7168b201f907dc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f67fe7b89bfbdcc1643ae9b96a7e5577f7a67861"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "22b3f3980f0701abda8e664e6cb0f2bba5faf2140e1d692d80f066a8052210c4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eb4cf717981c8963d950780b79476d485d4fa85"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3e3a9c6ecc0a2c148bcbdccc5cf1f92d389bc4c291cc389f8fc85ea5ce9cb235"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f892acd16d6885d25232682d01169b8fc4a94d4"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "153c8e11a83de3a1cd584274d2085033506539f9bee42fb26762f0d5820c467d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44a533f9b2bd46c279207e73a43bb4753e46a5d0"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b7229a55dfac6d87ba30a71c157bc44dc32dcca59ea847685cc8d0b61880826a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ddfe7aeeca74f8259ce65845a93456795b1d066"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6da1a9469ef95d46cff97e4c2fc3b009ad4234aa2315950a4653f6675093a78d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "069c685e30be56e852d77f361ee8541e9f35b6ae"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "5a77ba4f993808f314b5b55851e30e0ba44855da9c40189cd6db1551189b1d20"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9efa95d848671485eaa1d1fd07bc2f4877ecdc81"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "fe21c724ca808965e43b357e821b4f01778eb96c96adf7ad0f05293c978e6779"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d85485597d9ec1af931cece29426cbdb854549a8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "06cfeb5df82016ee4ece0fdf8e93ef45dc522555758747315c6eb060b0107398"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a45f3d5ee4598c6b896a5b5b9f856f33dca7cb89"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3230d8cb71e47386cc6bbc0c2ec5effd01ede79eafa2c27bc877d4349603459f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c48917b6e0632a29552454eca732fadf5486e962"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "ed371d789a8d08fe58d03bd7b6ddef3afbae5b8e782c770862c9c0cceee3bedc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d87ad8ece4202b00e95c42d669231758c8bd775f"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e41465698a98cfa336a071cf962d7e98c1f6098941c6259d874f15fa6918560f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95b84e385a11b5ee19200460abeebadb3f69ae29"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "91b13911dece230df1d797cdb257481199ad0b110ed846a00943fd2e04af3436"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ccf9a6e9b6d2da2ab583fc2d023efd4808582bd"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "10ce2057b532d76aad8d4522d618b4648ca3bed547c3a54c3a35e737df868691"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fc90188a9a94e3550e15f8eed72313cf302edb9"
os = "windows"

    [[Clang.download]]
    sha256 = "c4ca99aa06f9e3050a0ac5f8da39fe2f3c27b99fd5db66a5fea4e5deac4dedda"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0103e892bdca2c69193bf6a2e2bcec94a3ab91f3"
os = "windows"

    [[Clang.download]]
    sha256 = "0cf0d66082f657ecce131a65c9195145a97ed03e1133d7f50be36209ffcae918"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8ac8502998551e4bd2120fac58c9a9b56fd9f84"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "01a50a910eaf8fb790dc6f565bd07ae1dd5044ff5b45925f8be58773646669e4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7d1e4cb2ddec3c8f08ab5ade346f63c2c0427ce"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "11daf1e86e82bf6697040e1d27feb25434f6f4a3222bb8b3d27142ec5f88a864"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "81cf038b45db21beff2046ebd27717981b4d76f1"
os = "macos"

    [[Clang.download]]
    sha256 = "5630efbc145046d770d3fb72f3feddb600cfea89763c54dd5a49dcc83c62572d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a52f62397fee5dede7d42fe4d801cb2c2ad56ce"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "11eff8dce2d1ca95a634b42877de909e57cdd3b4e112fc6d39f6b9b83dabd734"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1716a6c0f37057e935e6b93fea86233ad27bba1a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f7f2c5091b32afb21d48182325b36f3e51bb1e525ee8588d8f4593f4f60c780b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79ed7ef9ae56103be7634ef0cb22256361786ccd"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "943035127ee9204ba23f09d63e330bf5e2497819e60b03eccf614aa58322d86f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "697e2b5a386f3f9f98ac2b8ca032d992ef034770"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "01ffc600c92f97f12b414573cca0bf0fa1d830fa1cad4794f459326f3d6d1f78"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "7c19bcf1ac91993083b3ffe2ef1b235c41694964"
os = "freebsd"

    [[Clang.download]]
    sha256 = "74c668a5fc1ac5c6d01cd462d7e5b0f534a689e76a5033a05561d292d1db74bf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7d6cc59d2ba7b254062e50a3a871303a697d198"
os = "windows"

    [[Clang.download]]
    sha256 = "3713256ccd5ef24cf2f3ee8a397447e51c8fb8c539b17e44d41c2c5b7f8d8bc7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1805cd3a0bedc3e30b2a8652e28a47ea319a2deb"
os = "windows"

    [[Clang.download]]
    sha256 = "434d49e3640d922825cd14da753a4baf9033bf6c7fa662c1e2c9f08f1850c9e9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.0+1/Clang.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
