[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52b0fe9970d98a4f981d3c8139c26c1275bb87a8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "779228cd5895c73c0a2884314a2f407e6191f2aad3312481b59d79119e4192ad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4318f6c419b88aea54fc006ad4065872780d192a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e561996cb009146e1379feaf21797edfaf8b213c31590798377434fb03e24685"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c1958baf7d33bf16e10fa96051d3d62dfe63ad8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "0458126b6609e08da3fbfcf89eed43202747e8aa88d5bb3ac880f7a47851c977"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "774d3b7127c9bddbdb84eecc63e03762630d05ad"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "047fb572c39a4f920cc06f13247244095f15f87001ce7bfff6679a4982b9f0da"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0eb78834672fb870f4b1ea48436b48308898f9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2587d7c736a9e03b7066655b180386ac085b64266396d08bfaebbce4fb6e9163"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fc3ff57692101a729211b7033bb4f22f07ae4a2"
os = "macos"

    [[Clang.download]]
    sha256 = "4a8ca1384b4f8c9d99e06370c1bc6031a79e9ab7dec22d0848a6a1799a4b7047"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9823d67b3964a723e78c6444df468857dec633d6"
os = "freebsd"

    [[Clang.download]]
    sha256 = "c2d98eb5166e158c84475b701ed4908f7e64699595fec09feb04b3da5253d068"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c16254c3373e9f8752795683645562d6a8e75f7"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "07ac0ddbf3c015d2ab4c8dc245aa60700baceca83cffa480fe090d92683bc34b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b3446c80936628fc15704410a45338b14b8e965"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "7f2ce1046504bafe8c6b5059e9972a50c05f9f5f6e7aca9690cbd741671a993e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "038fd29a2cba59e5dde4d6529ed8e37f19eed480"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "d5c1092962650bc5cc8d52717ad9d54bf4f3f7cee6c28ecd4046387c4c34b36d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df5e03d40bf19d8c3844a6a4fa3103d0c360251"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "d0c4e3cf388d628f56783d24d621a0f96e2d345443f97d1f3aae5004e3843629"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20840f498be7ed5f38b7607562533a8f9a312202"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6551d582e0254f38d1c794fefeb5b3d44765ee070753718e5d9e25d85f4bbfef"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82135c23a2827e2414051a5977f0e048c1c55221"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a9dfa7e93572891fbcddc9c4bcbea32f29297ffba89e60cea7c36eed8ca1b9aa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fc3ff57692101a729211b7033bb4f22f07ae4a2"
os = "macos"

    [[Clang.download]]
    sha256 = "a87103456ee22754f8b01eddbc84679356b82bcaa2cf3b6d1eda6749eefe31df"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00ad9e8d81e99fe1c90625509e2c280c67b59bd8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "212f10cedb106c315c94c28626e901bb4054ab0c415249cb21c57854964f310c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11d73871076a4b50369d4bf7066fdc65ed8be9f7"
os = "windows"

    [[Clang.download]]
    sha256 = "998faa3549a491b996f44adf67e031b3aa2b5c9d5c81b31ea8a17f3acec0d696"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "899e8791696e8e7bb2b561167fcb1748cd6ff0c9"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2346dd7cc80cd2689a9c518e04ddf44778e46791cdcca7aa10f5549c1aa89c7e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a006be925d7ef802d5ab986441736e92cdd36290"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "12226d20b3cc141d4dcf120307cac49456ec80a39deeda3e6fd2ee2c40384254"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee45980e6fd489d8231b621ccb2d918a74c37324"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "c2dfb4e830f663aa3d84cb9580f87243089f0d83f90f27a7eb48eb841d8115ca"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d03a2cbbce8104aac29c3291ce443c45054aa4c"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "35edf52e2e0fcc3a2cc5426fa8df526a37e249f28eef8652f25c7db7a569da36"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4a3d31df91f66cd6bd9be6a88f7af08403a68a4"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b851c94ea26fcb62427310b9d75ac433e1580843dfcf8c9c629a26e56a8b9eaf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cccb99da8689598be090d7e0706b64d0d1bd5062"
os = "windows"

    [[Clang.download]]
    sha256 = "e309ea7c1dcc721c4ec921e9fda146d96a664fd37e6e5cffb14f37a1b791ab2b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1eb346b985d04da636f494443dc773bb3b1030c"
os = "windows"

    [[Clang.download]]
    sha256 = "9efdba9d6a8caabb410247df6b2d282ad131a24313f424606c3d472611b415e0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d22b052687f3443f702c8fe1110022e33d7105c2"
os = "windows"

    [[Clang.download]]
    sha256 = "386d85e1e586b3045839375f513db00d601a5e07887baaf0e59aa304f39cc9f8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed67ed0dfe50d2ee018d4d135421af6cc209578b"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "a82d72ad73966602052d5194dd384d4ef5a5216551d6beb9834d083f1b8bdad0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9823d67b3964a723e78c6444df468857dec633d6"
os = "freebsd"

    [[Clang.download]]
    sha256 = "bf788a70e5844b4d85110f33fe9c0f5eccbcdd2a33cdd89a5904310b65a8cfac"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v9.0.1+1/Clang.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
