[[Clang]]
arch = "aarch64"
git-tree-sha1 = "c3f17ec4e59363a05d075f05555b80997da3c854"
os = "macos"

    [[Clang.download]]
    sha256 = "a94f3cedc84bc54dd12c33f38069442f8ed1ba3fbd035f74051c36c985ec22f5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "612920e6c047f4a3945f727b5261eda1dc474832"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2cfcfdf2a9d312b216b74a8eb9f61e4301797399e13b3dc050d989288d01a80a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3df68a65823d656e9e9c90bbd788748a30454936"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "4ddd25431c61a60ca144a496760bab973a83472787c5543628d8b202b034491d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57c0c742c32969ff7c413625034dd81e2bf16629"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "f448695e0622ca416bdd127fa76411897b837acd9cb6cd60b0aa2587d83a8339"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ed81300d20c9cf5948ff8e63483069e4fdbc584"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "8d23887f5ce99c57d926081d95af0c7d3604089c66c208b53bcbc94004e7826a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bbfd5d529a84ea8e2e98783ecd0b8db7902c34f"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b800cba0d60011abd9f8121fd2a7e343220a543b0c9fa4d0e7f3cac52dbff4cd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77f22b6738cb80059059d8180e58536e772a3168"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "2bf355ecea775a5aca23be824431730299eff0639c4a0eb36ac1c1500f515922"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d92c183c883155a7a71a5969b960966da774e294"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ad029f95d8f6b18124736080f890b024d2c171c65d40c09057a91c2b0f0b7841"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8da8a785d1f776862ff2b074c4cfe2677fd32850"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "440cee5e0f934159e093effa541bf8a23f7129b01828aed3c9011d006bcff8d6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9810422533a569d8a2327139e8878190d2d55ad"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "6cb9035de0da4de760007f381a83936f14fc9adfcc317efa1361428fe711c5e3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b379b44fd8924363637053ab4f0ac7d8e9edd7f8"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "21f218384558ad258f01776e8ba8144f197619989500ac228fbf9b6cf7069a69"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "193f9df00833cc8752bfe73890685d22f793cddb"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "64500ce5c9f156b57ce6cf8b6c353ce12d6264888f51930c47e143755ae2c520"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d58f6062dfd733f568e2525509ddbb5e1fc1c88"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "9a6b03064b738753981f5aa6482bb08bf7e79a815c75145d7ccfdb8ce2765bd3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1584246950dcd8892ad92198efec42b12a5e599c"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "f0381dc5313ff9a0d82b200a4a3b486f34e403cfc4879545470ccb18c540d483"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56adc90688376638e74deb189cf20bbf48757d53"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9c66507434be9ef153439e8296d37872f460336ba7735427c2c3bfbda6690710"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6986b174c14e27d28c1e5688cc010cfbd2f023f8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "0e60fc3e443709c56e894a3e89b10e7e077f69c154b2d4603ff7a4b5eb7dbe1f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c41ec85a54708aba5d5b617dae3f8c7c6847b85"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "90a02a8ad7dc53d232aed9a974a4608f67dc395b9e3b59c6ef661c220c552308"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "155c080c4a1cecfb4113dc9f5e1c9b9ca1c38a3e"
os = "windows"

    [[Clang.download]]
    sha256 = "b3db3170ba73e1e0cd303dff42706d93f9bc0c263e647a502c4cdb9ddbc5eea0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9293403ef6914894b1990ef457dfa56f339701a3"
os = "windows"

    [[Clang.download]]
    sha256 = "1c90f910d24e4cf70ddb029c88cd483bfc66cf598f719f0f334be41a52e2d732"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f52de6d880cdf34637d08064a987f6ee19287dec"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "1920960f16286ce7417bd5e4e736ef79ebed5520e2841da922403e4ece48b33d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "347fc6764c91bca1234e2654ddfd16e0ecb8cc08"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "39c823fb14cca8d166139ae7a64063a483801e2d3211b2d8d78f36cb2a262bfe"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "6d11f740b1d1a7f12fc792f3451770f4e7c7a87a"
os = "macos"

    [[Clang.download]]
    sha256 = "6be3a965ca2ff143598dbe32931c96860b9a47c04d2ac944ac064d2917b18c2b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecc3526523f8d6f81428e59299bf2e406e58ca1a"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "fe62aedad0a164fe9c7e5557cd8f5dc2ca87f7e974166241a4a68a0d4c146f63"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cc979407bf1498e1a1d9d8492e8c50a028831b3"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "fe47a3bacc93713d548089d5bc18f64692eb928775d639975911fac70e0fa657"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88479c017dd8e3f6a9040fd5cb68767428315bca"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "4b45d13d1152b81a089ba1d3866e9e17b0e4df40f47b99f6c491bc8a4af6055c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ba030044d590a408d48acbc2962a0b5439afe08"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "3328161a6c325df6f284bd0153884ea2a4f02cc27d85aac73616d1a5b78c12d2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "439a0cf21c9eaa9a001e97692f978209023014d4"
os = "freebsd"

    [[Clang.download]]
    sha256 = "78c198920398eda9a55a3b0e08e466bb4338777d4ea816b92aaa820d70747b77"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9473dc548c9949dec9bcc2de83f287a161828aa9"
os = "windows"

    [[Clang.download]]
    sha256 = "8008c159a205fe55745f93db79dc50fb08fc461213eb3d1c8537696456af0843"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90375e33a158f3ed2cb84bbb2b08c3e86b70c0a0"
os = "windows"

    [[Clang.download]]
    sha256 = "7866f33103dd6fc28aaffa037de3fad693c0fb26d6f6eec65e57de5d07de1955"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v13.0.1+1/Clang.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
