[[Clang]]
arch = "aarch64"
git-tree-sha1 = "b3eb91787ac1dd24a72cda84381d43807d264492"
os = "macos"

    [[Clang.download]]
    sha256 = "bf52786b98e4c023eea6d2aeace60db6efb451466d6e556db38fef3c77c04b3b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.aarch64-apple-darwin.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ae8a6a6445a849c7fae6e271bb6c26ca35c046d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "751303c88575b7a1376cd326a287ca88ff0849bd7bff912e5670a392ca02e521"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e83a80b40fd2062bf3c8c743cc7895b506d5437"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "25589bdb67a4858b8f11d0136181609ed65622c25e1f13ba40af53dc405a61c3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9134979cd9f11f57246d606f80a8e5061382ccb8"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d85d4ed0f54cb6ed4b6b67c226edada1c084b303ad1ad1d223310a9c60f48593"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0895ea8a7452dfc99ce7440e99fc52adeaa761ae"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d7c3ed766a381196fc0a2d4f62b9bf3f72437724a80fd919567f5c712342e2b2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d4a6ca035d7595825dc13306082d001da20168d"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "3f95c0aa1bc41968b694c3130e481d55ab40476517fea8ae211062839c0e9c7c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f63961f69fd318e39b84aa4ca477ebf2647c6b"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b395ec661baee87ae9e77784e2c8efbdd8e28bdbf50ebdbb02fcd6e15c45711b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a087f4262ddf6954e8730100bc533f2baa81a40"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "ba35ce7e2263f8368b3da9c3f1910935660e947ef63445be0401aa24dc5f9e1b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f658fbbff6e8afeb29a4bb41ab7c8a65505b23f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "5b6eeeaff748dcb9039841e63f661c50d878017565da12c1302fd9615d589e02"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56b448d025b9145c91f21406127c2fa050758081"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "b1e7295b5180a4ed179e47523f55a21b28b1e949776a0a487b1251153dad7fa3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01462118da5af89e9bec97b6c93a4486b0b303c"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "264af816b3a0247ae992c8c0750fec0f612ec5b6da73b4f0687c50b16ab006db"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c55a1f91db07dbd7849ebbb123495b5b929c93f"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6e4ba9ed64ae35cfe2e0a4e37a28585a71a33dc9fe256d8908d2933e89f314f3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c48f93b3d323a72922eaaa36417e725811392e"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "caf0f36903297e841f8a09f7cf789f97c583a2c00c13dfb09ce5e43fd9a94ff5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788013831bc029ecb96aa4f19579c2fc085c74ed"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "30ccb62b2a992b4c35af640f14a94ceff6a2f9f190adeba2e3a5011d6b1b09c7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18839b2869972f36a40545c74fb72c3c4addc0eb"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "8e9b90f3ec6bfedf70dd48f453a5665624709e84d0f34d0f62c890f1d0e65adb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0e70909d504365e2b70f68d64919d2151d479c7"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "82288a527c8cf3c18033fa43a76ccb5ca05e025dc31fc8417b9b9fedf38d8ecb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe5e47c22efd5029dd74cef9041654b471eecd64"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "d1b21e4ea6643976bfca5d6cf31d8979ad833bf24074cf954d6ec48f3d786ff2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bc868eae3590c3f1e0df2d007767ad66491a6ff"
os = "windows"

    [[Clang.download]]
    sha256 = "3e8f334bef0bb1aa4ef04e7a1c957006b6d5e372618eef1190e4853183b43ad2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f685779298c909919fb4f90c7e79cb7c34fcd93"
os = "windows"

    [[Clang.download]]
    sha256 = "bebeeb1492ce71f15c3c62006dd9cb03f01f811fe34b45856e3a57a6de21f723"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1dda18226dbea8a9656b19c1508ba579c7e5a59"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "855eb5841af9c98399ac455f487c7d66be89ed8c988b423825389d55f1e2e56f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1dd7da41381eb0f2ecae21a0beb1186e8345010"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "e4055343a07098e6ea191775cb7244e68c356de4e354c3096ddc252313f7546d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "c9c5685c3a76171eee93423d704fac7a4acafb23"
os = "macos"

    [[Clang.download]]
    sha256 = "d160d8fed9bec7dbdf3a09d3e7a313ff0e017394434e76d58c439755a112c966"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-apple-darwin.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dd41f6688856bc6cc320cc6429af2deca544a32"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "107f51256efe7494d0bf3f18a0e915d7ebb128615dc473821a575575aa8cc19e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8676d447ac19c510b147ae120378d2f57729b153"
libc = "glibc"
os = "linux"

    [[Clang.download]]
    sha256 = "9f91b7e4292bdc40804bcf85f105ecf523d502c07239e0d61853f50569b75e16"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "883fa609cc671c23da59a8279bfc0a13f1160dd5"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "6e8ab603e886e4cce73535c58e6001a576d28cb91d53634944e4e5aeebe33e11"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bf1e24794e8c106d1029ac06c0c1a6960310cb2"
libc = "musl"
os = "linux"

    [[Clang.download]]
    sha256 = "b6beabfc19e686c9b1d09d0f074feab11b505b9bd74f006106dd6b2d802984b0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang]]
arch = "x86_64"
git-tree-sha1 = "ae505dd4cfdc8b8b6be8280c2419e3da7fc46680"
os = "freebsd"

    [[Clang.download]]
    sha256 = "ab250cabae33ad89d8d0dd97b42fba71b14614f548a274b5747f0d2e359b4477"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cabf8135ab5025466f09102505304167963d03d2"
os = "windows"

    [[Clang.download]]
    sha256 = "995fab2903e80ae10d76ded3a2e51bf0e774c7aa85041af03a0194c52d641f03"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03af7183078ed5256bc545f547abb8a807232666"
os = "windows"

    [[Clang.download]]
    sha256 = "419f334e6318872cfe9eb3f733497bb5cf6de1f1aff490da1f8b050a3002f1f0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/download/Clang-v11.0.0+2/Clang.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
